import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const respond=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const shortLang=(v:string)=>v.trim().toLowerCase().split(/[-_]/)[0]||"en";
const sanitize=(v:string)=>v.replace(/https?:\/\/\S+/gi," ").replace(/www\.\S+/gi," ").replace(/[`*_#]+/g," ").replace(/[•●▪◦‣⁃]+/g,". ").replace(/(^|\n)\s*[-–—]+\s*/gm,". ").replace(/\s+/g," ").trim().slice(0,3600);

const locales:Record<string,string>={ar:"ar-XA",en:"en-GB",nl:"nl-NL",de:"de-DE",fr:"fr-FR",es:"es-ES",it:"it-IT",pt:"pt-BR",tr:"tr-TR",ru:"ru-RU",pl:"pl-PL",uk:"uk-UA",ro:"ro-RO",el:"el-GR",cs:"cs-CZ",sk:"sk-SK",hu:"hu-HU",bg:"bg-BG",hr:"hr-HR",sr:"sr-RS",sl:"sl-SI",sv:"sv-SE",no:"nb-NO",da:"da-DK",fi:"fi-FI",he:"he-IL",hi:"hi-IN",bn:"bn-IN",ta:"ta-IN",te:"te-IN",ml:"ml-IN",mr:"mr-IN",gu:"gu-IN",kn:"kn-IN",zh:"cmn-CN",ja:"ja-JP",ko:"ko-KR",th:"th-TH",vi:"vi-VN",id:"id-ID",sw:"sw-KE"};
const chirpVoice=(language:string)=>{const code=locales[shortLang(language)]??"en-GB";return{languageCode:code,name:`${code}-Chirp3-HD-Charon`}};

function b64ToBytes(value:string){const b=atob(value);const out=new Uint8Array(b.length);for(let i=0;i<b.length;i++)out[i]=b.charCodeAt(i);return out;}
function bytesToB64(bytes:Uint8Array){let out="";for(let i=0;i<bytes.length;i+=0x8000)out+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));return btoa(out);}
function ascii(v:DataView,o:number,s:string){for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i));}
function pcmToWav(pcm:Uint8Array,rate=24000){const b=new ArrayBuffer(44+pcm.length);const v=new DataView(b);ascii(v,0,"RIFF");v.setUint32(4,36+pcm.length,true);ascii(v,8,"WAVE");ascii(v,12,"fmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);ascii(v,36,"data");v.setUint32(40,pcm.length,true);new Uint8Array(b,44).set(pcm);return new Uint8Array(b);}
function b64urlBytes(bytes:Uint8Array){return bytesToB64(bytes).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function b64urlText(v:string){return b64urlBytes(new TextEncoder().encode(v))}

async function fetchJson(url:string,init:RequestInit,timeoutMs:number){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeoutMs);const started=Date.now();try{const r=await fetch(url,{...init,signal:c.signal});const j=await r.json().catch(()=>null);return{r,j,ms:Date.now()-started,error:""};}catch(e){return{r:null,j:null,ms:Date.now()-started,error:e instanceof DOMException&&e.name==="AbortError"?"timeout":String(e).slice(0,300)};}finally{clearTimeout(t)}}
async function serviceAccountAccess(raw:string){try{const sa=JSON.parse(raw);const email=String(sa?.client_email??"");const pem=String(sa?.private_key??"");const project=String(sa?.project_id??"");if(!email||!pem)return{token:null as string|null,project,error:"service_account_missing_fields"};const body=pem.replace(/-----BEGIN PRIVATE KEY-----/g,"").replace(/-----END PRIVATE KEY-----/g,"").replace(/\s+/g,"");const bin=atob(body);const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);const key=await crypto.subtle.importKey("pkcs8",bytes.buffer,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);const now=Math.floor(Date.now()/1000);const h=b64urlText(JSON.stringify({alg:"RS256",typ:"JWT"}));const p=b64urlText(JSON.stringify({iss:email,scope:"https://www.googleapis.com/auth/cloud-platform",aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+900}));const unsigned=`${h}.${p}`;const sig=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,new TextEncoder().encode(unsigned));const assertion=`${unsigned}.${b64urlBytes(new Uint8Array(sig))}`;const rr=await fetchJson("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion})},5000);const token=rr.r?.ok&&typeof rr.j?.access_token==="string"?rr.j.access_token:null;return{token,project,error:token?"":String(rr.j?.error_description??rr.j?.error??rr.error??`http_${rr.r?.status??0}`).slice(0,300)};}catch(e){return{token:null as string|null,project:"",error:String(e).slice(0,300)}}}

async function cloudChirp(text:string,language:string,key:string){const v=chirpVoice(language);const x=await fetchJson(`https://texttospeech.googleapis.com/v1/text:synthesize?key=${encodeURIComponent(key)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({input:{text},voice:v,audioConfig:{audioEncoding:"MP3"}})},8000);const audio=typeof x.j?.audioContent==="string"?x.j.audioContent:"";return{ok:Boolean(x.r?.ok&&audio),audio,mime:"audio/mpeg",provider:"google-cloud-chirp3",model:v.name,status:x.r?.status??0,detail:String(x.j?.error?.message??x.error??"").slice(0,300),ms:x.ms};}
async function cloudGemini(text:string,saRaw:string){const sa=await serviceAccountAccess(saRaw);if(!sa.token)return{ok:false,audio:"",mime:"",provider:"google-cloud-gemini-tts",model:"gemini-2.5-flash-tts/ar-EG/Charon",status:0,detail:sa.error,ms:0};const x=await fetchJson("https://texttospeech.googleapis.com/v1/text:synthesize",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${sa.token}`,...(sa.project?{"x-goog-user-project":sa.project}:{})},body:JSON.stringify({input:{prompt:"اتكلم بالمصري القاهري الطبيعي بصوت دكتور بيطري راجل، هادي ومهني. انطق النص كما هو بدون إضافة أو حذف.",text},voice:{languageCode:"ar-EG",name:"Charon",modelName:"gemini-2.5-flash-tts"},audioConfig:{audioEncoding:"MP3"}})},9000);const audio=typeof x.j?.audioContent==="string"?x.j.audioContent:"";return{ok:Boolean(x.r?.ok&&audio),audio,mime:"audio/mpeg",provider:"google-cloud-gemini-tts",model:"gemini-2.5-flash-tts/ar-EG/Charon",status:x.r?.status??0,detail:String(x.j?.error?.message??x.error??"").slice(0,300),ms:x.ms};}
async function geminiDirect(text:string,language:string,key:string){const ar=shortLang(language)==="ar";const prompt=ar?`SYNTHESIZE SPEECH ONLY. Speak the exact transcript as a natural Egyptian male veterinarian from Cairo. Warm professional tone, conversational rhythm. Do not add or remove words.\n\n${text}`:`SYNTHESIZE SPEECH ONLY. Read the exact transcript naturally in ${language}, warm professional male veterinarian voice. Do not add or remove words.\n\n${text}`;for(const model of ["gemini-2.5-flash-preview-tts","gemini-3.1-flash-tts-preview"]){const x=await fetchJson(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,{method:"POST",headers:{"x-goog-api-key":key,"content-type":"application/json"},body:JSON.stringify({contents:[{role:"user",parts:[{text:prompt}]}],generationConfig:{responseModalities:["AUDIO"],speechConfig:{voiceConfig:{prebuiltVoiceConfig:{voiceName:"Charon"}}}}})},9000);const part=x.j?.candidates?.[0]?.content?.parts?.find((p:any)=>p?.inlineData?.data||p?.inline_data?.data);const raw=part?.inlineData?.data??part?.inline_data?.data;if(x.r?.ok&&typeof raw==="string"&&raw){const wav=bytesToB64(pcmToWav(b64ToBytes(raw)));return{ok:true,audio:wav,mime:"audio/wav",provider:"gemini-generative-tts",model,status:x.r.status,detail:"",ms:x.ms};}if(model.includes("3.1"))return{ok:false,audio:"",mime:"",provider:"gemini-generative-tts",model,status:x.r?.status??0,detail:String(x.j?.error?.message??x.error??x.j?.candidates?.[0]?.finishReason??"empty_audio").slice(0,300),ms:x.ms};}return{ok:false,audio:"",mime:"",provider:"gemini-generative-tts",model:"none",status:0,detail:"no_audio",ms:0};}

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
  if(req.method!=="POST")return respond({error:"Method not allowed"},405);
  const admin=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false,autoRefreshToken:false}});
  const log=async(user_id:string|null,language:string|null,provider:string,model:string,outcome:string,status:number,detail:string)=>{try{await admin.from("voice_provider_events").insert({user_id,requested_language:language,provider,model_or_voice:model,outcome,http_status:status||null,detail:(detail||"").slice(0,500)||null});}catch(_){}};
  const auth=req.headers.get("Authorization");
  await log(null,null,"case-voice","v18","edge_entered",0,auth?"authorization_present":"authorization_missing");
  if(!auth)return respond({code:"VOICE_AUTH_MISSING"},401);
  const userClient=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_ANON_KEY")!,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});
  const {data:userData,error:userError}=await userClient.auth.getUser();
  if(userError||!userData.user){await log(null,null,"case-voice","v18","auth_failure",401,String(userError?.message??"invalid_session"));return respond({code:"VOICE_AUTH_INVALID"},401);}
  const body=await req.json().catch(()=>({}));const text=sanitize(typeof body?.text==="string"?body.text:"");const language=typeof body?.language==="string"&&body.language.trim()?body.language.trim().toLowerCase():"en";
  if(!text)return respond({error:"Text is required"},400);
  const uid=userData.user.id;await log(uid,language,"case-voice","v18","request_started",0,`lang=${language}; chars=${text.length}`);
  const googleKey=Deno.env.get("GOOGLE_API_KEY")?.trim()??"";const geminiKey=Deno.env.get("GEMINI_API_KEY")?.trim()??"";const saRaw=Deno.env.get("GOOGLE_CLOUD_TTS_SERVICE_ACCOUNT_JSON")?.trim()??"";
  await log(uid,language,"case-voice","v18","config",0,`google_key=${Boolean(googleKey)}; gemini_key=${Boolean(geminiKey)}; service_account=${Boolean(saRaw)}`);

  const tasks:Promise<any>[]=[];
  if(shortLang(language)==="ar"&&saRaw)tasks.push(cloudGemini(text,saRaw));
  if(geminiKey)tasks.push(geminiDirect(text,language,geminiKey));
  if(googleKey)tasks.push((async()=>{if(shortLang(language)==="ar")await new Promise(r=>setTimeout(r,1200));return cloudChirp(text,language,googleKey)})());
  if(tasks.length===0){await log(uid,language,"case-voice","v18","no_provider_configured",0,"No Google/Gemini TTS secret configured");return respond({code:"VOICE_NOT_CONFIGURED"},503);}

  const wrapped=tasks.map(p=>p.then(async r=>{await log(uid,language,r.provider,r.model,r.ok?"success":r.detail==="timeout"?"timeout":"failure",r.status,`${r.detail}; ${r.ms}ms`);if(!r.ok)throw new Error(`${r.provider}:${r.detail}`);return r;}));
  try{const winner=await Promise.any(wrapped);return respond({audio_base64:winner.audio,audioContent:winner.audio,mime_type:winner.mime,provider:winner.provider,voice:winner.model,requested_language:language,egyptian_style:shortLang(language)==="ar"&&winner.provider!=="google-cloud-chirp3",text_chars:text.length});}
  catch(e){await log(uid,language,"case-voice","v18","all_failed",503,String(e).slice(0,400));return respond({code:"VOICE_TEMPORARILY_UNAVAILABLE"},503);}
});
