import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const PRIMARY_MODEL = Deno.env.get("VET_AI_GEMINI_ANALYSIS_MODEL") ?? "gemini-3.6-flash";
const FALLBACK_MODEL = Deno.env.get("VET_AI_GEMINI_ANALYSIS_FALLBACK_MODEL") ?? "gemini-3.5-flash-lite";
const BASE = "https://generativelanguage.googleapis.com/v1beta/models";
const MAX_IMAGE_BYTES = 8 * 1024 * 1024;

const SCHEMA = {
  type:"object", additionalProperties:false,
  properties:{
    image_quality:{type:"string",enum:["insufficient","limited","adequate"]},
    group_match:{type:"string",enum:["match","mismatch","uncertain"]},
    group_match_reason:{type:"string"}, species_observed:{type:"string"},
    lesion_morphology:{type:"string",enum:["proliferative_crusts","vesicles_erosions","mixed","none","uncertain"]},
    visible_hypersalivation:{type:"boolean"}, visible_foot_lesions:{type:"boolean"},
    summary:{type:"string"}, observed_signs:{type:"array",maxItems:12,items:{type:"string"}},
    differentials:{type:"array",maxItems:5,items:{type:"object",additionalProperties:false,properties:{catalog_slug:{type:"string"},display_name:{type:"string"},suspicion:{type:"string",enum:["low","moderate","high"]},reasoning:{type:"string"}},required:["catalog_slug","display_name","suspicion","reasoning"]}},
    risk:{type:"string",enum:["none","yellow","orange","red","insufficient_data"]}, urgent_vet_review:{type:"boolean"}, isolation_recommended:{type:"boolean"}, lab_confirmation_required:{type:"boolean"},
    immediate_actions:{type:"array",maxItems:5,items:{type:"string"}}, follow_up_questions:{type:"array",maxItems:5,items:{type:"string"}}, confidence_statement:{type:"string"}
  },
  required:["image_quality","group_match","group_match_reason","species_observed","lesion_morphology","visible_hypersalivation","visible_foot_lesions","summary","observed_signs","differentials","risk","urgent_vet_review","isolation_recommended","lab_confirmation_required","immediate_actions","follow_up_questions","confidence_statement"]
};

const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const fail=(code:string,message:string,status=200,extra:Record<string,unknown>={})=>json({code,risk:"insufficient_data",message,...extra},status);
const clean=(v:unknown)=>String(v??"").replace(/https?:\/\/\S+/gi,"").replace(/\s{2,}/g," ").trim();
const cleanList=(v:unknown)=>Array.isArray(v)?v.map(clean).filter(Boolean):[];
const mimeFromPath=(p:string)=>{const e=p.split(".").pop()?.toLowerCase();return e==="jpg"||e==="jpeg"?"image/jpeg":e==="png"?"image/png":e==="webp"?"image/webp":null;};
const bytesToBase64=(bytes:Uint8Array)=>{let s="";for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));return btoa(s);};
const modelText=(payload:any)=>{for(const c of payload?.candidates??[]){const chunks:string[]=[];for(const p of c?.content?.parts??[]){if(p?.thought===true)continue;if(typeof p?.text==="string"&&p.text.length)chunks.push(p.text);}if(chunks.length)return chunks.join("").trim();}return null;};
const parseJson=(raw:string)=>{const v=raw.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim();try{return JSON.parse(v);}catch(_){}const f=v.indexOf("{");const l=v.lastIndexOf("}");if(f>=0&&l>f)return JSON.parse(v.slice(f,l+1));throw new Error("No complete JSON");};
const suspicionRank:Record<string,number>={high:3,moderate:2,low:1};
const smallRuminant=(s:string)=>/(sheep|goat|lamb|kid|ovine|caprine|غنم|خروف|ماعز|جدي|حمل)/i.test(s);
const cattleLike=(s:string)=>/(cattle|cow|calf|bull|heifer|bovine|buffalo|بقر|بقرة|عجل|جاموس)/i.test(s);
const dogLike=(s:string)=>/(dog|canine|puppy|كلب|جرو)/i.test(s);
const poultryLike=(s:string)=>/(chicken|chick|hen|rooster|broiler|layer|poultry|turkey|duck|goose|avian|دجاج|كتكوت|فراخ|بط|وز|ديك رومي)/i.test(s);
const historyStrongFmdSupport=(s:string)=>/(lameness|hoof|interdigital|foot lesion|blister|vesicle|عرج|حافر|بين الأظلاف|إصابة قدم|حويصل|فقاع)/i.test(s);
const oralSite=(s:string)=>/(lip|lips|muzzle|around the mouth|mouth margin|oral commissure|شفاه|الشفة|الخطم|حول الفم|حواف الفم)/i.test(s);
const crustEvidence=(s:string)=>/(crust|crusts|scab|scabs|proliferative|thickened|wart-like|قشر|قشور|جلبة|جلبات|تكاثري|ثؤلول)/i.test(s);
const genericScope=(x:string)=>/(all|any|livestock|ruminant|mammal|multiple species|عدة أنواع|مجترات)/i.test(x);
function speciesScopeMatches(scope:unknown,species:string){
  if(!Array.isArray(scope)||scope.length===0)return true;
  const items=scope.map(x=>clean(x).toLowerCase()).filter(Boolean);
  if(items.some(genericScope))return true;
  if(smallRuminant(species))return items.some(x=>/(sheep|lamb|goat|kid|ovine|caprine|غنم|خروف|ماعز|جدي|حمل)/i.test(x));
  if(cattleLike(species))return items.some(x=>/(cattle|cow|calf|bull|heifer|bovine|buffalo|بقر|عجل|جاموس)/i.test(x));
  if(dogLike(species))return items.some(x=>/(dog|canine|puppy|كلب|جرو)/i.test(x));
  if(poultryLike(species))return items.some(x=>/(chicken|chick|hen|rooster|broiler|layer|poultry|turkey|duck|goose|avian|دجاج|كتكوت|بط|وز|ديك)/i.test(x));
  return true;
}

Deno.serve(async(req:Request)=>{
 try{
  if(req.method!=="POST")return json({error:"Method not allowed"},405);
  const authorization=req.headers.get("Authorization");if(!authorization)return json({error:"Missing authorization"},401);
  const body=await req.json().catch(()=>({}));const assessmentId=typeof body?.assessment_id==="string"?body.assessment_id:"";const language=typeof body?.language==="string"?body.language.toLowerCase():"en";const ar=language.startsWith("ar");if(!assessmentId)return json({error:"assessment_id is required"},400);
  const key=Deno.env.get("GEMINI_API_KEY")?.trim();if(!key)return fail("GEMINI_NOT_CONFIGURED",ar?"خدمة الذكاء البيطري غير مهيأة حاليًا.":"The veterinary AI service is not configured.",503);
  const supabase=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_ANON_KEY")!,{global:{headers:{Authorization:authorization}},auth:{persistSession:false,autoRefreshToken:false}});
  const {data:authData,error:authError}=await supabase.auth.getUser();if(authError||!authData.user)return json({error:"Invalid session"},401);
  const {data:assessment,error:assessmentError}=await supabase.from("assessments").select("id,farm_id,media_path,symptom_notes,animal_group,species_code,bird_type").eq("id",assessmentId).single();
  if(assessmentError||!assessment)return json({error:"Assessment not found or access denied"},404);if(!assessment.media_path)return json({error:"Assessment has no image"},400);
  const animalGroup=assessment.animal_group??"livestock";const selectedSpecies=clean(assessment.species_code||assessment.bird_type);if(!selectedSpecies)return fail("SPECIES_REQUIRED",ar?"اختار نوع الحيوان قبل التحليل.":"Select the animal species before analysis.",400);
  const {data:allDiseases,error:diseaseError}=await supabase.from("disease_catalog").select("id,slug,display_name,animal_groups,cause,default_risk,treatment_summary,prevention_summary,owner_actions_summary,clinical_red_flags,isolation_guidance,lab_confirmation_required,zoonotic,reportable_or_listed,curation_status,species_scope,source_org,source_url").eq("curation_status","reviewed").order("display_name");
  if(diseaseError||!allDiseases)return fail("KNOWLEDGE_BASE_UNAVAILABLE",ar?"قاعدة المعرفة البيطرية غير متاحة مؤقتًا.":"Veterinary knowledge is temporarily unavailable.",503);
  const diseases=allDiseases.filter((d:any)=>Array.isArray(d.animal_groups)&&d.animal_groups.includes(animalGroup)&&speciesScopeMatches(d.species_scope,selectedSpecies));if(!diseases.length)return fail("KNOWLEDGE_GAP",ar?"لا توجد معرفة بيطرية مراجعة كافية للنوع المختار.":"No reviewed veterinary knowledge is available for this group.");
  const ids=diseases.map((d:any)=>d.id);const {data:signs}=await supabase.from("disease_signs").select("disease_id,phase,sign,visible_in_image").in("disease_id",ids);
  const modelCatalog=diseases.map((d:any)=>({slug:d.slug,name:d.display_name,cause:d.cause,default_risk:d.default_risk,lab_confirmation_required:d.lab_confirmation_required,zoonotic:d.zoonotic,reportable_or_listed:d.reportable_or_listed,species_scope:d.species_scope,source_org:d.source_org,visible_signs:(signs??[]).filter((s:any)=>s.disease_id===d.id&&s.visible_in_image===true).map((s:any)=>({phase:s.phase,sign:s.sign}))}));
  const {data:blob,error:mediaError}=await supabase.storage.from("diagnostic-media").download(assessment.media_path);if(mediaError||!blob)return json({error:"Image unavailable or access denied"},404);if(blob.size>MAX_IMAGE_BYTES)return fail("IMAGE_TOO_LARGE",ar?"الصورة كبيرة جدًا للتحليل.":"Image too large.");
  const mime=mimeFromPath(assessment.media_path);if(!mime)return fail("UNSUPPORTED_IMAGE_FORMAT",ar?"استخدم JPEG أو PNG أو WEBP.":"Use JPEG, PNG or WEBP.");const image=bytesToBase64(new Uint8Array(await blob.arrayBuffer()));
  const langRule=ar?"اكتب كل النصوص التي يراها المستخدم بالعربية المصرية المهنية فقط، بدون خلط جمل إنجليزية.":`Write all user-facing fields naturally in language code ${language}.`;
  const prompt=`You are Vet AI, a conservative veterinary decision-support triage system. ${langRule}\nSelected animal group: ${animalGroup}\nUSER-SELECTED SPECIES (authoritative): ${selectedSpecies}\nSymptoms/history: ${assessment.symptom_notes?.trim()||"None supplied"}\nReviewed diagnostic catalog; ONLY these catalog_slug values may be returned:\n${JSON.stringify(modelCatalog)}\n\nMANDATORY VISUAL ORDER:\n1) Identify species first. 2) Describe lesion morphology without disease names. 3) Decide if true fluid-filled vesicles/fresh erosions are actually visible. 4) Decide whether hypersalivation and foot/interdigital lesions are visible. 5) Only then rank diseases.\nDefinitions: proliferative_crusts = thick adherent proliferative scabs/crusts. vesicles_erosions = actual fluid-filled blisters or fresh erosions compatible with ruptured vesicles. Never label a crust/scab as a blister.\nSPECIES RULE: species_scope is binding. The user-selected species is authoritative for catalog filtering. Use species_observed only to detect a possible image/selection mismatch; never silently switch species. Never return a disease whose species_scope excludes the user-selected species.\nFMD SAFETY RULE: HIGH image suspicion for FMD requires vesicles_erosions or mixed morphology PLUS strong corroboration from foot/interdigital lesions or compatible supplied history. Hypersalivation by itself is NOT enough for HIGH FMD suspicion. Crusted lip/muzzle lesions alone are NOT high evidence for FMD.\nORF RULE: in sheep/goats/lambs/kids, thick proliferative crusts around lips/muzzle strongly favor Orf/contagious ecthyma over FMD when Orf exists in the catalog and true vesicles/foot lesions are absent.\nNever make a definitive diagnosis from one image. Rank by morphology + species + history, not by severity or reportable status. Never invent drug doses or withdrawal periods.`;
  const call=async(model:string,timeoutMs:number)=>{const c=new AbortController();const t=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(`${BASE}/${encodeURIComponent(model)}:generateContent`,{method:"POST",signal:c.signal,headers:{"x-goog-api-key":key,"content-type":"application/json"},body:JSON.stringify({contents:[{role:"user",parts:[{text:prompt},{inline_data:{mime_type:mime,data:image}}]}],generationConfig:{temperature:0.05,maxOutputTokens:3200,responseMimeType:"application/json",responseJsonSchema:SCHEMA}})});const p=await r.json().catch(()=>null);return{r,p};}finally{clearTimeout(t);}};
  let parsed:any=null,payload:any=null,usedModel="",requestId="";const failures:string[]=[];
  for(const a of [{model:PRIMARY_MODEL,timeout:24000},{model:FALLBACK_MODEL,timeout:20000}].filter((a,i,r)=>r.findIndex(x=>x.model===a.model)===i)){try{const z=await call(a.model,a.timeout);payload=z.p;requestId=String(payload?.responseId??z.r.headers.get("x-request-id")??requestId);if(!z.r.ok||!payload){failures.push(`${a.model}:${z.r.status}`);continue;}const raw=modelText(payload);try{parsed=raw?parseJson(raw):null;}catch(_){parsed=null;}if(parsed&&String(payload?.candidates?.[0]?.finishReason??"")!=="MAX_TOKENS"){usedModel=a.model;break;}failures.push(`${a.model}:invalid_json`);}catch(e){failures.push(`${a.model}:${e instanceof DOMException&&e.name==="AbortError"?"timeout":"exception"}`);}}
  if(!parsed||!usedModel)return fail("GEMINI_TEMPORARILY_UNAVAILABLE",ar?"تعذر إكمال التحليل الآن. حاول مرة أخرى.":"Analysis unavailable; retry shortly.",503,{provider_request_id:requestId||null,attempts:failures});
  const m=parsed;const allowed=new Map(diseases.map((d:any)=>[d.slug,d]));
  let diffs=(Array.isArray(m.differentials)?m.differentials:[]).filter((d:any)=>allowed.has(String(d?.catalog_slug??""))).slice(0,5).map((d:any)=>{const c:any=allowed.get(String(d.catalog_slug));return{catalog_slug:c.slug,name:clean(d.display_name||c.display_name),suspicion:["low","moderate","high"].includes(d.suspicion)?d.suspicion:"low",reasoning:clean(d.reasoning),cause:clean(c.cause),default_risk:c.default_risk,zoonotic:c.zoonotic,reportable_or_listed:c.reportable_or_listed,lab_confirmation_required:c.lab_confirmation_required,diagnostics_required:Boolean(c.lab_confirmation_required),prevention_summary:clean(c.prevention_summary),treatment_summary:clean(c.treatment_summary),owner_actions_summary:clean(c.owner_actions_summary),clinical_red_flags:cleanList(c.clinical_red_flags),isolation_guidance:clean(c.isolation_guidance),species_scope:Array.isArray(c.species_scope)?c.species_scope:[]};});
  const morphology=["proliferative_crusts","vesicles_erosions","mixed","none","uncertain"].includes(m.lesion_morphology)?m.lesion_morphology:"uncertain";const salivation=m.visible_hypersalivation===true;const foot=m.visible_foot_lesions===true;const speciesObserved=clean(m.species_observed);const species=selectedSpecies;const small=smallRuminant(species);const historySupport=historyStrongFmdSupport(String(assessment.symptom_notes??""));const strongFmd=(morphology==="vesicles_erosions"||morphology==="mixed")&&(foot||historySupport);const observedText=[clean(m.summary),...cleanList(m.observed_signs)].join(" ");const oralCrustPattern=small&&(morphology==="proliferative_crusts"||(oralSite(observedText)&&crustEvidence(observedText)));
  diffs=diffs.filter((d:any)=>speciesScopeMatches(d.species_scope,selectedSpecies));
  diffs=diffs.map((d:any)=>{if(d.catalog_slug==="fmd"&&!strongFmd){return{...d,suspicion:(morphology==="vesicles_erosions"||morphology==="mixed")?"moderate":"low",reasoning:ar?"الحمى القلاعية تظل مرضًا مهمًا للاستبعاد، لكن الاشتباه المرتفع يحتاج حويصلات/تآكلات متوافقة مع دليل أقوى مثل إصابات القدم/بين الأظلاف أو تاريخ سريري مناسب. اللعاب وحده لا يكفي.":"FMD remains an important rule-out, but high suspicion requires compatible vesicles/erosions plus stronger corroboration such as foot/interdigital lesions or compatible history. Salivation alone is not enough."};}if(d.catalog_slug==="orf"&&oralCrustPattern){return{...d,suspicion:"high",reasoning:ar?"في الأغنام أو الماعز، القشور التكاثرية أو الجلبات الملتصقة حول الشفاه والخطم تتوافق مع الأورف أكثر من الحمى القلاعية عندما لا توجد أدلة قوية على حويصلات وإصابات قدم.":"In sheep/goats, proliferative adherent crusts around the lips/muzzle are more compatible with Orf than FMD when strong vesicular/foot evidence is absent."};}return d;});
  if(oralCrustPattern&&!diffs.some((d:any)=>d.catalog_slug==="orf")&&allowed.has("orf")){const c:any=allowed.get("orf");diffs.unshift({catalog_slug:"orf",name:ar?"الأورف (التهاب الفم المعدي)":c.display_name,suspicion:"high",reasoning:ar?"شكل القشور التكاثرية الملتصقة حول الشفاه والخطم في الأغنام أو الماعز يضع الأورف ضمن أعلى الاحتمالات المرئية، مع بقاء التأكيد البيطري مطلوبًا.":"Proliferative adherent crusts around the lips/muzzle in a sheep/goat place Orf high in the image differential; veterinary confirmation is still required.",cause:clean(c.cause),default_risk:c.default_risk,zoonotic:c.zoonotic,reportable_or_listed:c.reportable_or_listed,lab_confirmation_required:c.lab_confirmation_required,diagnostics_required:true,prevention_summary:clean(c.prevention_summary),treatment_summary:clean(c.treatment_summary),owner_actions_summary:clean(c.owner_actions_summary),clinical_red_flags:cleanList(c.clinical_red_flags),isolation_guidance:clean(c.isolation_guidance),species_scope:Array.isArray(c.species_scope)?c.species_scope:[]});}
  diffs.sort((a:any,b:any)=>{if(oralCrustPattern){if(a.catalog_slug==="orf")return-1;if(b.catalog_slug==="orf")return 1;if(a.catalog_slug==="fmd"&&!strongFmd)return 1;if(b.catalog_slug==="fmd"&&!strongFmd)return-1;}return(suspicionRank[b.suspicion]??0)-(suspicionRank[a.suspicion]??0);});diffs=diffs.slice(0,5);
  const groupMatch=["match","mismatch","uncertain"].includes(m.group_match)?m.group_match:"uncertain";let risk=["none","yellow","orange","red","insufficient_data"].includes(m.risk)?m.risk:"insufficient_data";if(oralCrustPattern&&!strongFmd&&risk==="red")risk="orange";
  const result={code:groupMatch==="mismatch"?"SPECIES_GROUP_MISMATCH":"AI_ANALYSIS_COMPLETE",assessment_id:assessmentId,animal_group:animalGroup,selected_species:selectedSpecies,group_match:groupMatch,image_quality:["insufficient","limited","adequate"].includes(m.image_quality)?m.image_quality:"limited",species_observed:speciesObserved,lesion_morphology:morphology,visible_hypersalivation:salivation,visible_foot_lesions:foot,summary:clean(groupMatch==="mismatch"?(m.group_match_reason||m.summary):m.summary),observed_signs:groupMatch==="mismatch"?[]:cleanList(m.observed_signs).slice(0,12),differential_diagnoses:groupMatch==="mismatch"?[]:diffs,risk:groupMatch==="mismatch"?"insufficient_data":risk,urgent_vet_review:groupMatch==="mismatch"?false:m.urgent_vet_review===true,isolation_recommended:groupMatch==="mismatch"?false:m.isolation_recommended===true,lab_confirmation_required:groupMatch==="mismatch"?false:m.lab_confirmation_required===true,immediate_actions:groupMatch==="mismatch"?[]:cleanList(m.immediate_actions).slice(0,5),follow_up_questions:groupMatch==="mismatch"?[]:cleanList(m.follow_up_questions).slice(0,5),confidence_statement:clean(m.confidence_statement),report_stage:"triage",provider:"gemini",model:usedModel,provider_request_id:requestId||null,failover_used:usedModel!==PRIMARY_MODEL,generated_at:new Date().toISOString(),guardrails:{fmd_high_evidence:strongFmd,small_ruminant_crust_rule:oralCrustPattern,species_scope_enforced:true}};
  const {error:saveError}=await supabase.from("assessments").update({observed_signs:result.observed_signs,differential_diagnoses:result.differential_diagnoses,risk:result.risk,isolation_recommended:result.isolation_recommended,urgent_vet_review:result.urgent_vet_review,lab_confirmation_required:result.lab_confirmation_required,status:"ai_review",ai_analysis:result,ai_model:usedModel,ai_provider_request_id:requestId||null,ai_usage:{...(payload?.usageMetadata??{}),failover_used:usedModel!==PRIMARY_MODEL,attempts:failures},ai_generated_at:result.generated_at}).eq("id",assessmentId);if(saveError)return fail("AI_RESULT_SAVE_FAILED",ar?"تم إنشاء التحليل لكن تعذر حفظه.":"Analysis generated but could not be saved.",500);
  await supabase.from("alerts").delete().eq("assessment_id",assessmentId);if(result.risk==="red"||result.risk==="orange")await supabase.from("alerts").insert({farm_id:assessment.farm_id,assessment_id:assessmentId,risk:result.risk,title:ar?(result.risk==="red"?"تنبيه صحي عاجل من Vet AI":"حالة محتاجة مراجعة بيطرية"):(result.risk==="red"?"Urgent Vet AI health alert":"Vet AI veterinary review alert"),details:result.summary});
  return json(result);
 }catch(error){console.error("analyze-case-unhandled",error);return fail("ANALYSIS_INTERNAL_ERROR","The analysis service hit an internal error. Please retry.",500);}
});