from pathlib import Path

APP = Path('lib/legal/vet_legal_pages.dart')
text = APP.read_text(encoding='utf-8')

MARKER = 'EU-LEGAL-V43'
if MARKER in text:
    print('Vet AI EU legal pages V43 already applied')
    raise SystemExit(0)

# Make the information hub and legal-detail pages substantially larger/readable.
replacements = {
    "style: const TextStyle(fontSize: 25, fontWeight: FontWeight.w900)":
        "style: const TextStyle(fontSize: 29, fontWeight: FontWeight.w900)",
    "style: const TextStyle(color: VetColors.muted, height: 1.55, fontSize: 15.5)":
        "style: const TextStyle(color: VetColors.muted, height: 1.6, fontSize: 17)",
    "leading: Container(width: 48, height: 48, decoration: BoxDecoration(color: page.color.withValues(alpha: .1), borderRadius: BorderRadius.circular(14)), child: Icon(page.icon, color: page.color, size: 28))":
        "leading: Container(width: 62, height: 62, decoration: BoxDecoration(color: page.color.withValues(alpha: .1), borderRadius: BorderRadius.circular(18)), child: Icon(page.icon, color: page.color, size: 33))",
    "title: Text(page.title, style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 17))":
        "title: Text(page.title, style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 20.5))",
    "subtitle: Padding(padding: const EdgeInsets.only(top: 5), child: Text(page.subtitle, style: const TextStyle(height: 1.35)))":
        "subtitle: Padding(padding: const EdgeInsets.only(top: 7), child: Text(page.subtitle, style: const TextStyle(height: 1.5, fontSize: 15.3)))",
    "Text(data.title, style: const TextStyle(fontSize: 29, fontWeight: FontWeight.w900, height: 1.15))":
        "Text(data.title, style: const TextStyle(fontSize: 34, fontWeight: FontWeight.w900, height: 1.15))",
    "Text(data.intro, style: const TextStyle(fontSize: 16, color: VetColors.muted, height: 1.55))":
        "Text(data.intro, style: const TextStyle(fontSize: 18, color: VetColors.muted, height: 1.65))",
    "Text(section.title, style: TextStyle(fontSize: 19, fontWeight: FontWeight.w900, color: color))":
        "Text(section.title, style: TextStyle(fontSize: 21.5, fontWeight: FontWeight.w900, color: color, height: 1.25))",
    "Text(section.body, style: const TextStyle(fontSize: 15, height: 1.6))":
        "Text(section.body, style: const TextStyle(fontSize: 16.3, height: 1.7))",
    "Expanded(child: Text(item, style: const TextStyle(fontSize: 14.5, height: 1.5)))":
        "Expanded(child: Text(item, style: const TextStyle(fontSize: 15.8, height: 1.62)))",
}
for old, new in replacements.items():
    if old not in text:
        raise SystemExit(f'EU legal V43 layout marker missing: {old[:80]}')
    text = text.replace(old, new, 1)

# A prominent, repeated boundary notice on every detailed legal/information page.
intro_marker = """          Text(data.intro, style: const TextStyle(fontSize: 18, color: VetColors.muted, height: 1.65)),
          const SizedBox(height: 18),
          for (final section in data.sections) _SectionCard(section: section, color: data.color),"""
intro_replacement = """          Text(data.intro, style: const TextStyle(fontSize: 18, color: VetColors.muted, height: 1.65)),
          const SizedBox(height: 16),
          // EU-LEGAL-V43 — visible safe-use boundary on every legal page.
          Container(
            padding: const EdgeInsets.all(17),
            decoration: BoxDecoration(
              color: VetColors.orange.withValues(alpha: .09),
              borderRadius: BorderRadius.circular(18),
              border: Border.all(color: VetColors.orange.withValues(alpha: .28)),
            ),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Icon(Icons.warning_amber_rounded, color: VetColors.orange, size: 29),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    _lt(
                      context,
                      'Important: Vet AI is an information, early-warning and decision-support tool. It is not a veterinarian, veterinary clinic, laboratory, emergency service or autonomous treatment system. Never diagnose, prescribe, inject, change or stop medication, determine a food-animal withdrawal period, or delay urgent veterinary care solely because of an AI output.',
                      'مهم: Vet AI أداة معلومات وإنذار مبكر ودعم قرار. هو مش طبيب بيطري، ولا عيادة، ولا معمل، ولا خدمة طوارئ، ولا نظام علاج تلقائي. ممنوع تعتمد على نتيجة الذكاء الاصطناعي وحدها في تشخيص نهائي أو وصف دواء أو حقن أو تغيير/إيقاف دواء أو تحديد فترة سحب اللبن أو اللحوم أو تأخير الرعاية البيطرية العاجلة.',
                      'Belangrijk: Vet AI is een informatie-, vroege-waarschuwings- en beslissingsondersteunend hulpmiddel. Het is geen dierenarts, kliniek, laboratorium, spoeddienst of autonoom behandelsysteem. Gebruik AI-uitvoer nooit als enige basis voor diagnose, recept, injectie, wijziging/stopzetting van medicatie, wachttijd bij voedselproducerende dieren of uitstel van urgente veterinaire zorg.',
                    ),
                    style: const TextStyle(fontSize: 15.5, height: 1.58, fontWeight: FontWeight.w700),
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 20),
          for (final section in data.sections) _SectionCard(section: section, color: data.color),"""
if intro_marker not in text:
    raise SystemExit('EU legal V43 detail notice insertion marker missing')
text = text.replace(intro_marker, intro_replacement, 1)

safety_transition = """      ]);
    case LegalPageType.knowledge:"""
safety_extra = r"""        _LegalSection(_lt(c, 'Human oversight and no autonomous treatment', 'الإشراف البشري وعدم العلاج التلقائي', 'Menselijk toezicht en geen autonome behandeling'), _lt(c, 'Vet AI is intended to support a person who remains responsible for checking the real animal and the full context. The system must not autonomously start, stop or change treatment. Clinical and medicinal decisions that require professional judgement remain with a licensed veterinarian under the law that applies where the animal is located.', 'Vet AI معمول علشان يساعد شخص يفضل مسؤول عن فحص الحيوان الحقيقي والسياق الكامل. النظام ممنوع يبدأ أو يوقف أو يغير علاج تلقائيًا. القرارات السريرية والدوائية اللي محتاجة حكم مهني تفضل للطبيب البيطري المرخّص حسب القانون المطبق في مكان الحيوان.', 'Vet AI ondersteunt een persoon die verantwoordelijk blijft voor controle van het echte dier en de volledige context. Het systeem mag niet autonoom behandeling starten, stoppen of wijzigen. Klinische en medicamenteuze beslissingen die professioneel oordeel vereisen blijven bij een bevoegde dierenarts volgens het recht waar het dier zich bevindt.')),
        _LegalSection(_lt(c, 'No veterinary-client-patient relationship', 'لا ينشئ علاقة طبيب بيطري بالمستخدم والحيوان', 'Geen dierenarts-cliënt-patiëntrelatie'), _lt(c, 'Use of Vet AI by itself does not create a veterinary-client-patient relationship and does not mean that a veterinarian has examined the animal. A professional relationship exists only where a separately identified licensed veterinarian accepts responsibility in accordance with applicable veterinary law and professional rules.', 'استخدام Vet AI لوحده ما ينشئش علاقة طبيب بيطري-عميل-حيوان وما يعنيش إن طبيب فحص الحيوان. العلاقة المهنية تحصل فقط لو طبيب بيطري مرخّص ومحدد قبل المسؤولية طبقًا لقانون وممارسة الطب البيطري المطبقين.', 'Gebruik van Vet AI alleen creëert geen dierenarts-cliënt-patiëntrelatie en betekent niet dat een dierenarts het dier heeft onderzocht. Een professionele relatie ontstaat alleen wanneer een afzonderlijk geïdentificeerde bevoegde dierenarts verantwoordelijkheid aanvaardt volgens toepasselijk veterinair recht en beroepsregels.')),
        _LegalSection(_lt(c, 'Never delay urgent care', 'ممنوع تأخير الرعاية العاجلة', 'Stel urgente zorg nooit uit'), _lt(c, 'Do not wait for another scan, a notification or a support reply if the animal has severe breathing difficulty, collapse, uncontrolled bleeding, major trauma, seizures, severe bloat, inability to rise, rapidly worsening condition, suspected poisoning, severe dehydration, extreme pain, mass mortality or another immediately dangerous condition. Contact an appropriate veterinarian or emergency service without delay.', 'ماتستناش فحص جديد أو إشعار أو رد الدعم لو الحيوان عنده صعوبة تنفس شديدة أو انهيار أو نزيف غير متحكم فيه أو إصابة كبيرة أو تشنجات أو انتفاخ شديد أو مش قادر يقف أو حالته بتسوء بسرعة أو اشتباه تسمم أو جفاف شديد أو ألم شديد أو نفوق جماعي أو أي حالة خطر فوري. اتواصل مع طبيب بيطري أو خدمة طوارئ مناسبة فورًا.', 'Wacht niet op een nieuwe scan, melding of supportantwoord bij ernstige benauwdheid, instorten, ongecontroleerde bloeding, groot trauma, insulten, ernstige tympanie, niet kunnen opstaan, snelle verslechtering, vergiftigingsverdenking, ernstige uitdroging, extreme pijn, massale sterfte of ander direct gevaar. Neem onmiddellijk contact op met een passende dierenarts of spoeddienst.')),
        _LegalSection(_lt(c, 'User competence and staff training', 'كفاءة المستخدم وتدريب العاملين', 'Competentie en training van gebruikers'), _lt(c, 'The account holder is responsible for ensuring that people who operate Vet AI understand the limitations of AI, are trained for their assigned role, protect account credentials and do not make decisions beyond their competence. A business should define who may record observations, review results, escalate cases and make animal-health decisions.', 'صاحب الحساب مسؤول عن إن الأشخاص اللي بيستخدموا Vet AI يفهموا حدود الذكاء الاصطناعي وياخدوا تدريب مناسب لدورهم ويحافظوا على بيانات الدخول ومياخدوش قرارات خارج كفاءتهم. الشركة لازم تحدد مين يسجل الملاحظات ومين يراجع النتائج ومين يصعّد الحالات ومين ياخد قرارات صحة الحيوان.', 'De accounthouder moet zorgen dat gebruikers AI-beperkingen begrijpen, passend zijn getraind, inloggegevens beschermen en niet buiten hun competentie beslissen. Een bedrijf hoort vast te leggen wie observaties registreert, resultaten beoordeelt, casussen opschaalt en diergezondheidsbeslissingen neemt.')),
        _LegalSection(_lt(c, 'AI transparency', 'شفافية الذكاء الاصطناعي', 'AI-transparantie'), _lt(c, 'Users should be clearly informed when they are interacting with an AI feature and should be able to understand the intended use and important limitations. A confident tone, polished explanation, probability score or risk colour must never be treated as proof that an output is medically correct.', 'لازم يكون واضح للمستخدم لما يكون بيتعامل مع ميزة ذكاء اصطناعي ولازم يفهم الاستخدام المقصود والحدود المهمة. النبرة الواثقة أو شكل الإجابة المرتب أو نسبة الاحتمال أو لون الخطورة عمرهم ما يكونوا دليل إن النتيجة صحيحة طبيًا.', 'Gebruikers moeten duidelijk weten wanneer zij met een AI-functie werken en het beoogde gebruik en belangrijke beperkingen kunnen begrijpen. Een zelfverzekerde toon, nette uitleg, kansscore of risicokleur is nooit bewijs dat de uitkomst medisch juist is.')),
"""
if safety_transition not in text:
    raise SystemExit('EU legal V43 safety transition missing')
text = text.replace(safety_transition, safety_extra + safety_transition, 1)

privacy_transition = """      ]);
    case LegalPageType.terms:"""
privacy_extra = r"""        _LegalSection(_lt(c, 'EU/GDPR readiness and controller identity', 'الجاهزية للاتحاد الأوروبي وهوية مسؤول البيانات', 'EU/AVG-gereedheid en identiteit verantwoordelijke'), _lt(c, 'Before a public commercial launch, the privacy notice must identify the real legal entity acting as controller, its postal address, privacy contact and, where legally required, a data protection officer or EU representative. The privacy text must match the real technical data flows; a policy page alone cannot make processing GDPR-compliant.', 'قبل الإطلاق التجاري العام لازم سياسة الخصوصية تحدد الكيان القانوني الحقيقي المسؤول عن البيانات وعنوانه البريدي وطريقة التواصل للخصوصية، ولو القانون يطلب، مسؤول حماية البيانات أو ممثل داخل الاتحاد الأوروبي. الكلام المكتوب لازم يطابق تدفق البيانات الحقيقي؛ صفحة سياسة لوحدها ما تخليش المعالجة متوافقة مع GDPR.', 'Vóór openbare commerciële lancering moet de privacyverklaring de echte juridische entiteit als verwerkingsverantwoordelijke, postadres, privacycontact en waar wettelijk vereist FG of EU-vertegenwoordiger noemen. De tekst moet overeenkomen met feitelijke gegevensstromen; een beleidspagina alleen maakt verwerking niet AVG-conform.')),
        _LegalSection(_lt(c, 'GDPR purposes and legal bases', 'أغراض المعالجة والأسس القانونية في GDPR', 'AVG-doeleinden en rechtsgronden'), _lt(c, 'Each processing purpose must have an appropriate legal basis. Depending on the feature this may include performance of a contract, requested pre-contract steps, a legal obligation, a properly balanced legitimate interest, or consent for genuinely optional processing. A camera or location permission in iOS/Android is a technical permission and is not automatically the same as GDPR consent.', 'كل غرض لمعالجة البيانات لازم يكون له أساس قانوني مناسب. حسب الميزة ممكن يكون تنفيذ عقد أو خطوات قبل العقد بطلب المستخدم أو التزام قانوني أو مصلحة مشروعة بعد موازنة صحيحة أو موافقة لمعالجة اختيارية فعلًا. إذن الكاميرا أو الموقع في iOS/Android إذن تقني ومش تلقائيًا هو نفس موافقة GDPR.', 'Elk verwerkingsdoel vereist een passende rechtsgrond. Afhankelijk van de functie kan dit uitvoering van een overeenkomst, gevraagde precontractuele stappen, wettelijke verplichting, zorgvuldig afgewogen gerechtvaardigd belang of toestemming voor echt optionele verwerking zijn. Een camera- of locatiemachtiging in iOS/Android is technisch en niet automatisch hetzelfde als AVG-toestemming.')),
        _LegalSection(_lt(c, 'Your GDPR rights', 'حقوقك تحت GDPR', 'Uw AVG-rechten'), _lt(c, 'Where GDPR applies, individuals may have rights to information, access, correction, erasure, restriction, data portability, objection, withdrawal of consent where consent is relied upon, and complaint to the competent data-protection authority. Requests may require identity verification and lawful exceptions may apply.', 'لما GDPR ينطبق، الشخص ممكن يكون له حقوق في المعرفة والوصول والتصحيح والحذف وتقييد المعالجة ونقل البيانات والاعتراض وسحب الموافقة لما تكون هي الأساس وتقديم شكوى لجهة حماية البيانات المختصة. الطلب ممكن يحتاج تحقق من الهوية وممكن تنطبق استثناءات قانونية.', 'Waar de AVG geldt kunnen betrokkenen rechten hebben op informatie, inzage, correctie, wissing, beperking, dataportabiliteit, bezwaar, intrekking van toestemming waar die de grondslag is en klacht bij de bevoegde toezichthouder. Identiteitscontrole en wettelijke uitzonderingen kunnen gelden.')),
        _LegalSection(_lt(c, 'International transfers', 'نقل البيانات خارج المنطقة الاقتصادية الأوروبية', 'Internationale doorgifte'), _lt(c, 'If personal data is transferred outside the European Economic Area, the controller must use a lawful transfer mechanism where required, such as an adequacy decision or appropriate safeguards including standard contractual clauses, and carry out any required transfer assessment. Vet AI must not promise EU-only storage unless that is technically true.', 'لو البيانات الشخصية بتتنقل خارج المنطقة الاقتصادية الأوروبية، مسؤول البيانات لازم يستخدم آلية نقل قانونية عند الحاجة زي قرار كفاية أو ضمانات مناسبة ومنها البنود التعاقدية القياسية ويعمل أي تقييم نقل مطلوب. Vet AI مينفعش يقول إن التخزين داخل أوروبا فقط إلا لو ده صحيح تقنيًا فعلًا.', 'Als persoonsgegevens buiten de EER worden doorgegeven, moet waar vereist een geldige doorgiftegrond worden gebruikt, zoals een adequaatheidsbesluit of passende waarborgen waaronder standaardcontractbepalingen, plus vereiste beoordeling. Vet AI mag geen uitsluitend EU-opslag beloven tenzij dat technisch waar is.')),
        _LegalSection(_lt(c, 'Automated decisions and profiling', 'القرارات الآلية والبروفايل', 'Geautomatiseerde besluiten en profilering'), _lt(c, 'Vet AI is intended for animal-health decision support, not solely automated decisions that create legal or similarly significant effects on a natural person. If a future feature changes that position, the controller must assess the additional GDPR requirements and safeguards before deployment and update this notice.', 'Vet AI هدفه دعم قرارات صحة الحيوان، مش اتخاذ قرارات آلية بالكامل لها أثر قانوني أو أثر مشابه مهم على شخص طبيعي. لو ميزة مستقبلية غيرت ده، مسؤول البيانات لازم يقيّم متطلبات وضمانات GDPR الإضافية قبل تشغيلها ويحدث السياسة.', 'Vet AI is bedoeld voor ondersteuning van diergezondheidsbeslissingen, niet voor uitsluitend geautomatiseerde besluiten met rechtsgevolg of vergelijkbaar significant effect op een natuurlijke persoon. Als een toekomstige functie dit verandert, moeten extra AVG-eisen en waarborgen vóór inzet worden beoordeeld en deze verklaring worden aangepast.')),
        _LegalSection(_lt(c, 'Connected products and the EU Data Act', 'الأجهزة المتصلة وقانون البيانات الأوروبي', 'Verbonden producten en de EU Data Act'), _lt(c, 'Where connected Vet AI hardware or a related service falls within the EU Data Act, the commercial product information must accurately describe the product and related-service data generated, how often it is collected, where it is stored, how the user can access or retrieve it, relevant metadata and applicable retention. Data Act access rights are separate from GDPR rights over personal data.', 'لو أجهزة Vet AI المتصلة أو خدمة مرتبطة بيها دخلت تحت قانون البيانات الأوروبي، معلومات المنتج التجارية لازم توضح بدقة نوع بيانات المنتج والخدمة اللي بتتولد وتكرار جمعها ومكان تخزينها وإزاي المستخدم يوصل لها أو يسترجعها والـmetadata اللازمة ومدة الاحتفاظ. حقوق قانون البيانات منفصلة عن حقوق GDPR في البيانات الشخصية.', 'Wanneer verbonden Vet AI-hardware of een gerelateerde dienst onder de EU Data Act valt, moet commerciële productinformatie nauwkeurig beschrijven welke product-/dienstdata ontstaat, frequentie, opslag, toegang/ophalen, relevante metadata en bewaartermijn. Data Act-rechten staan naast AVG-rechten op persoonsgegevens.')),
        _LegalSection(_lt(c, 'Security incidents and breach duties', 'حوادث الأمان والتزامات اختراق البيانات', 'Beveiligingsincidenten en datalekplichten'), _lt(c, 'Appropriate technical and organisational security measures should be used, but no internet service can promise absolute security. Suspected personal-data breaches must be assessed promptly and notified to the competent authority and affected individuals where GDPR requires. Users should report suspected unauthorised access without delay.', 'لازم تستخدم تدابير أمان تقنية وتنظيمية مناسبة، لكن مفيش خدمة إنترنت تقدر تضمن أمان مطلق. أي اشتباه في اختراق بيانات شخصية لازم يتقيّم بسرعة ويتم إخطار الجهة المختصة والأشخاص المتأثرين لما GDPR يطلب. المستخدم لازم يبلغ فورًا عن أي دخول غير مصرح مشتبه فيه.', 'Passende technische en organisatorische beveiliging is vereist, maar geen internetdienst kan absolute veiligheid beloven. Vermoedelijke persoonsgegevensinbreuken moeten snel worden beoordeeld en waar de AVG dit vereist gemeld aan toezichthouder en betrokkenen. Gebruikers moeten vermoedelijke ongeautoriseerde toegang direct melden.')),
"""
if privacy_transition not in text:
    raise SystemExit('EU legal V43 privacy transition missing')
text = text.replace(privacy_transition, privacy_extra + privacy_transition, 1)

terms_tail = """      ]);
  }
}

enum LegalPageType"""
terms_extra = r"""        _LegalSection(_lt(c, '13. Informational support, not treatment', '13. دعم معلوماتي وليس علاج', '13. Informatieve ondersteuning, geen behandeling'), _lt(c, 'Vet AI is supplied as an information, early-warning and decision-support tool. The service is not a veterinary clinic, laboratory, pharmacy or emergency service and does not itself provide a final professional diagnosis or prescription. General preventive or management information must not be represented as individual veterinary treatment.', 'Vet AI بيتقدم كأداة معلومات وإنذار مبكر ودعم قرار. الخدمة مش عيادة ولا معمل ولا صيدلية ولا خدمة طوارئ ومابتقدمش بنفسها تشخيص مهني نهائي أو وصفة. المعلومات الوقائية أو الإدارية العامة مينفعش تتقدم على إنها علاج بيطري فردي.', 'Vet AI wordt geleverd als informatie-, vroege-waarschuwings- en beslissingsondersteunend hulpmiddel. De dienst is geen kliniek, laboratorium, apotheek of spoeddienst en geeft zelf geen definitieve professionele diagnose of recept. Algemene preventieve/managementinformatie mag niet als individuele veterinaire behandeling worden voorgesteld.')),
        _LegalSection(_lt(c, '14. User remains responsible for action', '14. المستخدم يفضل مسؤول عن التصرف', '14. Gebruiker blijft verantwoordelijk voor handelen'), _lt(c, 'The user remains responsible for observing the real animal, providing accurate information, applying farm procedures, seeking professional care when appropriate and complying with veterinary, animal-welfare, food-safety, disease-control and reporting obligations. Vet AI must not be used to justify neglect or delay.', 'المستخدم يفضل مسؤول عن متابعة الحيوان الحقيقي وتقديم معلومات صحيحة وتطبيق إجراءات المزرعة وطلب رعاية مهنية عند الحاجة والالتزام بقواعد الطب البيطري والرفق بالحيوان وسلامة الغذاء ومكافحة الأمراض والإبلاغ. Vet AI ممنوع يستخدم لتبرير الإهمال أو التأخير.', 'De gebruiker blijft verantwoordelijk voor observatie van het echte dier, juiste informatie, bedrijfsprocedures, professionele zorg waar nodig en naleving van veterinaire, dierenwelzijns-, voedselveiligheids-, ziektebestrijdings- en meldplichten. Vet AI mag verwaarlozing of uitstel niet rechtvaardigen.')),
        _LegalSection(_lt(c, '15. Mandatory rights and fair liability limits', '15. الحقوق الإلزامية وحدود المسؤولية العادلة', '15. Dwingende rechten en eerlijke aansprakelijkheidsgrenzen'), _lt(c, 'Any commercial disclaimer, exclusion or liability cap must comply with the law that applies to the customer and must be fair and transparent. Nothing in these terms removes rights or liability that cannot legally be waived or limited, including mandatory consumer protections where applicable. A disclaimer cannot protect unlawful conduct or replace real safety controls.', 'أي إخلاء أو استثناء أو حد للمسؤولية في النسخة التجارية لازم يتوافق مع القانون المطبق على العميل ويكون عادل وواضح. مفيش حاجة في الشروط تلغي حقوق أو مسؤولية القانون ما يسمحش بالتنازل عنها أو تحديدها، ومنها حقوق المستهلك الإلزامية عند انطباقها. إخلاء المسؤولية ما يحميش تصرف غير قانوني وما يغنيش عن ضوابط أمان حقيقية.', 'Elke commerciële disclaimer, uitsluiting of aansprakelijkheidslimiet moet passen bij het toepasselijke recht en eerlijk/transparant zijn. Niets neemt rechten of aansprakelijkheid weg die wettelijk niet kunnen worden uitgesloten of beperkt, waaronder dwingende consumentenbescherming waar van toepassing. Een disclaimer beschermt geen onrechtmatig gedrag en vervangt geen echte veiligheidsmaatregelen.')),
        _LegalSection(_lt(c, '16. EU and national veterinary rules', '16. قواعد الاتحاد الأوروبي والقواعد الوطنية البيطرية', '16. EU- en nationale veterinaire regels'), _lt(c, 'EU animal-health and veterinary-medicines rules may apply together with national veterinary-practice, animal-welfare, food-safety and reporting law. Where signs suggest a listed/reportable disease, official authority procedures take priority. Medicine approval, prescription and withdrawal requirements must be followed; the app does not override them.', 'قواعد صحة الحيوان والأدوية البيطرية في الاتحاد الأوروبي ممكن تطبق مع قواعد ممارسة الطب البيطري والرفق بالحيوان وسلامة الغذاء والإبلاغ في كل دولة. لو العلامات تشير لمرض مدرج أو واجب الإبلاغ عنه، إجراءات الجهة الرسمية لها الأولوية. اعتماد الدواء والوصفة وفترات السحب لازم تتطبق والتطبيق ما يلغيش القواعد دي.', 'EU-regels voor diergezondheid en diergeneesmiddelen kunnen samen gelden met nationaal veterinair, dierenwelzijns-, voedselveiligheids- en meldingsrecht. Bij tekenen van een vermelde/meldingsplichtige ziekte hebben officiële procedures voorrang. Toelating, voorschrift en wachttijd moeten worden gevolgd; de app zet die niet opzij.')),
        _LegalSection(_lt(c, '17. AI Act transparency and literacy', '17. شفافية قانون الذكاء الاصطناعي والتوعية', '17. AI Act-transparantie en geletterdheid'), _lt(c, 'Where applicable, users should be informed that they are interacting with AI, and people operating AI on behalf of a business should have an appropriate level of AI literacy for their role and risk context. Vet AI documentation and interface should describe intended use, foreseeable misuse and important limitations in clear language.', 'عند انطباق القواعد، المستخدم لازم يعرف إنه بيتعامل مع ذكاء اصطناعي، والأشخاص اللي بيشغلوه نيابة عن شركة لازم يكون عندهم مستوى مناسب من فهم الذكاء الاصطناعي حسب دورهم ومستوى المخاطر. مستندات وواجهة Vet AI لازم توضح الاستخدام المقصود وسوء الاستخدام المتوقع والحدود المهمة بلغة واضحة.', 'Waar van toepassing moeten gebruikers weten dat zij met AI werken en personen die AI namens een bedrijf bedienen passende AI-geletterdheid hebben voor hun rol en risico-context. Documentatie en interface van Vet AI horen beoogd gebruik, voorzienbaar misbruik en belangrijke beperkingen duidelijk te beschrijven.')),
        _LegalSection(_lt(c, '18. Connected-device data rights', '18. حقوق بيانات الأجهزة المتصلة', '18. Rechten op gegevens van verbonden apparaten'), _lt(c, 'Where the EU Data Act applies to connected products or related services, users may have statutory rights to access relevant product and related-service data and metadata. Commercial hardware terms must not contradict those mandatory rights and should explain data generation, storage, access, sharing and termination arrangements.', 'لو قانون البيانات الأوروبي ينطبق على الأجهزة المتصلة أو الخدمات المرتبطة، المستخدم ممكن يكون له حقوق قانونية في الوصول لبيانات المنتج والخدمة والـmetadata. شروط الأجهزة التجارية مينفعش تتعارض مع الحقوق الإلزامية دي ولازم توضح توليد البيانات والتخزين والوصول والمشاركة وإنهاء الخدمة.', 'Wanneer de EU Data Act geldt voor verbonden producten of diensten kunnen gebruikers wettelijke rechten hebben op relevante product-/dienstdata en metadata. Commerciële hardwarevoorwaarden mogen die dwingende rechten niet tegenspreken en horen datageneratie, opslag, toegang, delen en beëindiging uit te leggen.')),
        _LegalSection(_lt(c, '19. Final company details, complaints and governing law', '19. بيانات الشركة النهائية والشكاوى والقانون المختص', '19. Definitieve bedrijfsgegevens, klachten en toepasselijk recht'), _lt(c, 'Before public commercial launch, the final terms must identify the contracting legal entity, registered/postal address, customer contact route, complaint process, applicable subscription/cancellation rules, governing law and competent forum. These choices must not unlawfully deprive a consumer of mandatory protections or remove the jurisdiction of a competent regulator or data-protection/animal-health authority.', 'قبل الإطلاق التجاري العام، الشروط النهائية لازم تحدد الكيان القانوني المتعاقد والعنوان المسجل/البريدي وطريقة التواصل والشكاوى وقواعد الاشتراك/الإلغاء والقانون المختص والجهة القضائية المختصة. الاختيارات دي مينفعش تحرم مستهلك بشكل غير قانوني من حقوقه الإلزامية ولا تلغي اختصاص جهة رقابية أو حماية بيانات أو صحة حيوان.', 'Vóór openbare commerciële lancering moeten de definitieve voorwaarden de contracterende juridische entiteit, geregistreerd/postadres, contact, klachtenproces, abonnement/opzegging, toepasselijk recht en bevoegde instantie noemen. Dit mag consumenten niet onrechtmatig dwingende bescherming ontnemen en beperkt geen bevoegde toezichthouder of gegevensbeschermings-/diergezondheidsautoriteit.')),
"""
if terms_tail not in text:
    raise SystemExit('EU legal V43 terms tail missing')
text = text.replace(terms_tail, terms_extra + terms_tail, 1)

# Update the policy version/footer wording without pretending a page alone creates compliance.
old_footer = "Policy version: 4 September 2026. Before a public commercial launch, jurisdiction-specific legal entity, address, tax and governing-law details should be reviewed by qualified legal counsel and inserted into the final public terms."
new_footer = "Policy version: 8 September 2026. Expanded EU-oriented safety, privacy and terms draft. Before public commercial launch, the real legal entity/controller identity, address, privacy contact, processors/transfers, retention schedule, customer model, taxes, governing law and country-specific veterinary rules must match the real service and should be reviewed by qualified legal counsel. Mandatory legal rights cannot be removed by an in-app disclaimer."
old_footer_ar = "إصدار السياسات: 4 سبتمبر 2026. قبل الإطلاق التجاري العام لازم بيانات الكيان القانوني والعنوان والضرائب والقانون المختص تتراجع مع محامي مؤهل وتتضاف للنسخة النهائية المنشورة من الشروط."
new_footer_ar = "إصدار السياسات: 8 سبتمبر 2026. تم توسيع الأمان والخصوصية والشروط بشكل موجه للاتحاد الأوروبي. قبل الإطلاق التجاري العام لازم هوية الكيان القانوني ومسؤول البيانات والعنوان ووسيلة الخصوصية والمعالجين/نقل البيانات ومدد الاحتفاظ ونوع العملاء والضرائب والقانون المختص والقواعد البيطرية لكل دولة تطابق الخدمة الحقيقية وتتراجع مع محامي مؤهل. الحقوق الإلزامية بالقانون ماينفعش تتشال بإخلاء مسؤولية داخل التطبيق."
old_footer_nl = "Beleidsversie: 4 september 2026. Voor een openbare commerciële lancering moeten rechtsvorm, adres, belasting- en toepasselijk-rechtgegevens door gekwalificeerd juridisch advies worden beoordeeld en in de definitieve voorwaarden worden opgenomen."
new_footer_nl = "Beleidsversie: 8 september 2026. Veiligheid, privacy en voorwaarden zijn uitgebreid met een EU-gerichte opzet. Vóór openbare commerciële lancering moeten de echte juridische entiteit/verwerkingsverantwoordelijke, adres, privacycontact, verwerkers/doorgiften, bewaarschema, klantmodel, belastingen, toepasselijk recht en nationale veterinaire regels overeenkomen met de echte dienst en door gekwalificeerd juridisch advies worden beoordeeld. Dwingende rechten kunnen niet door een in-app disclaimer worden uitgesloten."
for old, new in [(old_footer, new_footer), (old_footer_ar, new_footer_ar), (old_footer_nl, new_footer_nl)]:
    if old not in text:
        raise SystemExit('EU legal V43 footer marker missing')
    text = text.replace(old, new, 1)

APP.write_text(text, encoding='utf-8')

check = APP.read_text(encoding='utf-8')
required = [
    MARKER,
    'No veterinary-client-patient relationship',
    'Your GDPR rights',
    'Connected products and the EU Data Act',
    'AI Act transparency and literacy',
    'Mandatory rights and fair liability limits',
    'Policy version: 8 September 2026',
]
for item in required:
    if item not in check:
        raise SystemExit(f'EU legal V43 verification missing: {item}')

print('Vet AI V43 expanded EU-oriented legal, privacy and safety pages applied')
