from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if new in text:
        return text
    if old not in text:
        raise SystemExit(f'V73: {label} anchor missing')
    return text.replace(old, new, 1)


# ---------------------------------------------------------------------------
# 1) Chat send/receive cues without external asset files.
#    V70 referenced assets/audio/*.wav, but those files are generated only in
#    transient build stages in some paths and can be absent on GitHub Pages.
#    Generate the short cues in memory so browser + app always have them.
# ---------------------------------------------------------------------------
Path('lib/support/support_chat_sound.dart').write_text(r'''import 'dart:math' as math;
import 'dart:typed_data';

import 'package:audioplayers/audioplayers.dart';
import 'package:shared_preferences/shared_preferences.dart';

class VetSupportChatSound {
  VetSupportChatSound._();

  static final AudioPlayer _sendPlayer = AudioPlayer();
  static final AudioPlayer _receivePlayer = AudioPlayer();
  static const _prefKey = 'vet_ai_support_chat_muted';
  static bool _unlocked = false;
  static bool _muted = false;
  static bool _initialized = false;
  static String? _lastReceiveMessageId;
  static DateTime? _lastReceiveAt;

  // Original Vet AI cues. They are intentionally short and messenger-like,
  // but generated by Vet AI rather than copied from a third-party app.
  static final Uint8List _sendBytes = _tone(
    durationMs: 94,
    frequencies: const [1120.0, 1610.0],
    weights: const [0.68, 0.32],
    amplitude: .36,
    glide: .09,
    tailPower: 2.9,
  );
  static final Uint8List _receiveBytes = _tone(
    durationMs: 174,
    frequencies: const [720.0, 1080.0, 1460.0],
    weights: const [0.46, 0.34, 0.20],
    amplitude: .33,
    glide: .12,
    tailPower: 2.25,
  );
  static final Uint8List _silentBytes = _tone(
    durationMs: 22,
    frequencies: const [900.0],
    weights: const [1.0],
    amplitude: 0,
    glide: 0,
    tailPower: 2,
  );

  static bool get muted => _muted;

  static Future<void> initialize() async {
    if (_initialized) return;
    _initialized = true;
    try {
      final prefs = await SharedPreferences.getInstance();
      _muted = prefs.getBool(_prefKey) ?? false;
    } catch (_) {}
    try { await _sendPlayer.setReleaseMode(ReleaseMode.stop); } catch (_) {}
    try { await _receivePlayer.setReleaseMode(ReleaseMode.stop); } catch (_) {}
  }

  static Future<void> setMuted(bool value) async {
    _muted = value;
    _initialized = true;
    if (value) {
      try { await _sendPlayer.stop(); } catch (_) {}
      try { await _receivePlayer.stop(); } catch (_) {}
    }
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setBool(_prefKey, value);
    } catch (_) {}
  }

  /// Prime both browser audio players during a real user gesture.
  static Future<void> unlock() async {
    if (_muted || _unlocked) return;
    _unlocked = true;
    try {
      final a = _sendPlayer.play(BytesSource(_silentBytes), volume: .001, position: Duration.zero);
      final b = _receivePlayer.play(BytesSource(_silentBytes), volume: .001, position: Duration.zero);
      await Future.wait<void>([a, b]);
      try { await _sendPlayer.stop(); } catch (_) {}
      try { await _receivePlayer.stop(); } catch (_) {}
    } catch (_) {
      _unlocked = false;
    }
  }

  static Future<void> playSend() async {
    if (_muted) return;
    _unlocked = true;
    try {
      // Prime receive at the same tap moment so a subsequent incoming message
      // is allowed to make a sound in Safari after user interaction.
      final receivePrime = _receivePlayer.play(BytesSource(_silentBytes), volume: .001, position: Duration.zero);
      final sendStart = _sendPlayer.play(BytesSource(_sendBytes), volume: .92, position: Duration.zero);
      await sendStart;
      try {
        await receivePrime;
        await _receivePlayer.stop();
      } catch (_) {}
    } catch (_) {}
  }

  static Future<void> playReceive() => playReceiveFor('');

  static Future<void> playReceiveFor(String messageId) async {
    if (_muted) return;
    final now = DateTime.now();
    if (messageId.isNotEmpty &&
        _lastReceiveMessageId == messageId &&
        _lastReceiveAt != null &&
        now.difference(_lastReceiveAt!) < const Duration(seconds: 5)) {
      return;
    }
    _lastReceiveMessageId = messageId.isEmpty ? _lastReceiveMessageId : messageId;
    _lastReceiveAt = now;
    try {
      await _receivePlayer.play(BytesSource(_receiveBytes), volume: .90, position: Duration.zero);
    } catch (_) {}
  }

  static Uint8List _tone({
    required int durationMs,
    required List<double> frequencies,
    required List<double> weights,
    required double amplitude,
    required double glide,
    required double tailPower,
  }) {
    const sampleRate = 24000;
    const bytesPerSample = 2;
    final count = (sampleRate * durationMs / 1000).round();
    final dataLength = count * bytesPerSample;
    final data = ByteData(44 + dataLength);

    void ascii(int offset, String value) {
      for (var i = 0; i < value.length; i++) {
        data.setUint8(offset + i, value.codeUnitAt(i));
      }
    }

    ascii(0, 'RIFF');
    data.setUint32(4, 36 + dataLength, Endian.little);
    ascii(8, 'WAVE');
    ascii(12, 'fmt ');
    data.setUint32(16, 16, Endian.little);
    data.setUint16(20, 1, Endian.little);
    data.setUint16(22, 1, Endian.little);
    data.setUint32(24, sampleRate, Endian.little);
    data.setUint32(28, sampleRate * bytesPerSample, Endian.little);
    data.setUint16(32, bytesPerSample, Endian.little);
    data.setUint16(34, 16, Endian.little);
    ascii(36, 'data');
    data.setUint32(40, dataLength, Endian.little);

    for (var i = 0; i < count; i++) {
      final t = i / sampleRate;
      final p = i / count;
      final attack = math.min(1.0, i / (sampleRate * .002));
      final decay = math.pow(1.0 - p, tailPower).toDouble();
      final pitch = 1.0 + glide * p;
      var wave = 0.0;
      for (var n = 0; n < frequencies.length; n++) {
        final w = n < weights.length ? weights[n] : 1.0 / frequencies.length;
        wave += math.sin(2 * math.pi * frequencies[n] * pitch * t) * w;
      }
      final sample = (32767 * amplitude * attack * decay * wave)
          .round()
          .clamp(-32767, 32767)
          .toInt();
      data.setInt16(44 + i * 2, sample, Endian.little);
    }
    return data.buffer.asUint8List();
  }
}
''', encoding='utf-8')


# ---------------------------------------------------------------------------
# 2) Recorder + in-chat voice player.
#    - actual microphone PCM level is exposed live
#    - WAV is uploaded as a real audio message
#    - received/sent audio renders as a WhatsApp-style play/pause waveform,
#      never as a generic document card
# ---------------------------------------------------------------------------
Path('lib/support/support_voice_note.dart').write_text(r'''import 'dart:async';
import 'dart:typed_data';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/material.dart';
import 'package:record/record.dart';

import '../services/vet_backend.dart';

class VetSupportVoiceClip {
  const VetSupportVoiceClip(this.bytes, this.duration);
  final Uint8List bytes;
  final Duration duration;
}

class VetSupportVoiceRecorder {
  final AudioRecorder _recorder = AudioRecorder();
  final List<Uint8List> _chunks = <Uint8List>[];
  final ValueNotifier<double> level = ValueNotifier<double>(0);
  StreamSubscription<Uint8List>? _subscription;
  Completer<void>? _streamDone;
  DateTime? _startedAt;
  bool _recording = false;
  bool _paused = false;

  bool get recording => _recording;
  bool get paused => _paused;

  Future<void> start() async {
    if (_recording) return;
    final allowed = await _recorder.hasPermission();
    if (!allowed) throw StateError('Microphone permission denied');
    _chunks.clear();
    level.value = 0;
    _streamDone = Completer<void>();
    final stream = await _recorder.startStream(
      const RecordConfig(
        encoder: AudioEncoder.pcm16bits,
        sampleRate: 16000,
        numChannels: 1,
        autoGain: true,
        echoCancel: true,
        noiseSuppress: true,
      ),
    );
    _subscription = stream.listen(
      (chunk) {
        if (chunk.isEmpty) return;
        _chunks.add(Uint8List.fromList(chunk));
        _updateLevel(chunk);
      },
      onDone: () {
        if (_streamDone?.isCompleted == false) _streamDone?.complete();
      },
      onError: (Object error, StackTrace stack) {
        if (_streamDone?.isCompleted == false) _streamDone?.complete();
      },
      cancelOnError: false,
    );
    _startedAt = DateTime.now();
    _paused = false;
    _recording = true;
  }

  void _updateLevel(Uint8List pcm) {
    if (!_recording || _paused || pcm.length < 2) {
      level.value = 0;
      return;
    }
    final data = ByteData.sublistView(pcm);
    var peak = 0;
    // Sampling every 8 PCM frames keeps this cheap even on Safari.
    for (var i = 0; i + 1 < pcm.length; i += 16) {
      final value = data.getInt16(i, Endian.little).abs();
      if (value > peak) peak = value;
    }
    final normalized = (peak / 32768.0).clamp(0.0, 1.0).toDouble();
    final boosted = (normalized * 2.8).clamp(0.0, 1.0).toDouble();
    level.value = (level.value * .45 + boosted * .55).clamp(0.0, 1.0).toDouble();
  }

  Future<void> pause() async {
    if (!_recording || _paused) return;
    await _recorder.pause();
    _paused = true;
    level.value = 0;
  }

  Future<void> resume() async {
    if (!_recording || !_paused) return;
    await _recorder.resume();
    _paused = false;
  }

  Future<VetSupportVoiceClip?> stop() async {
    if (!_recording) return null;
    final started = _startedAt ?? DateTime.now();
    _recording = false;
    _paused = false;
    level.value = 0;
    await _recorder.stop();
    try {
      await _streamDone?.future.timeout(const Duration(milliseconds: 1800));
    } catch (_) {}
    await _subscription?.cancel();
    _subscription = null;
    final rawLength = _chunks.fold<int>(0, (sum, e) => sum + e.length);
    if (rawLength < 3200) {
      _chunks.clear();
      throw StateError('VOICE_RECORDING_TOO_SHORT');
    }
    final raw = Uint8List(rawLength);
    var offset = 0;
    for (final chunk in _chunks) {
      raw.setRange(offset, offset + chunk.length, chunk);
      offset += chunk.length;
    }
    _chunks.clear();
    final elapsed = DateTime.now().difference(started);
    final sampleDuration = Duration(milliseconds: ((rawLength / 2 / 16000) * 1000).round());
    final duration = sampleDuration.inMilliseconds > 0 ? sampleDuration : elapsed;
    return VetSupportVoiceClip(_wav(raw), duration);
  }

  Future<void> cancel() async {
    if (_recording) {
      _recording = false;
      _paused = false;
      try { await _recorder.cancel(); } catch (_) {}
    }
    level.value = 0;
    await _subscription?.cancel();
    _subscription = null;
    _chunks.clear();
  }

  void dispose() {
    unawaited(cancel());
    unawaited(_recorder.dispose());
    level.dispose();
  }

  static Uint8List _wav(Uint8List pcm) {
    const sampleRate = 16000;
    const channels = 1;
    const bits = 16;
    final out = ByteData(44 + pcm.length);
    void ascii(int at, String s) {
      for (var i = 0; i < s.length; i++) out.setUint8(at + i, s.codeUnitAt(i));
    }
    ascii(0, 'RIFF');
    out.setUint32(4, 36 + pcm.length, Endian.little);
    ascii(8, 'WAVE');
    ascii(12, 'fmt ');
    out.setUint32(16, 16, Endian.little);
    out.setUint16(20, 1, Endian.little);
    out.setUint16(22, channels, Endian.little);
    out.setUint32(24, sampleRate, Endian.little);
    out.setUint32(28, sampleRate * channels * bits ~/ 8, Endian.little);
    out.setUint16(32, channels * bits ~/ 8, Endian.little);
    out.setUint16(34, bits, Endian.little);
    ascii(36, 'data');
    out.setUint32(40, pcm.length, Endian.little);
    out.buffer.asUint8List().setRange(44, 44 + pcm.length, pcm);
    return out.buffer.asUint8List();
  }
}

class VetSupportVoiceService {
  VetSupportVoiceService._();

  static Future<void> send({
    required String threadId,
    required String senderRole,
    required VetSupportVoiceClip clip,
  }) async {
    if (senderRole != 'user' && senderRole != 'support') {
      throw ArgumentError('Invalid support sender role');
    }
    final backend = VetBackend.instance;
    final user = backend.currentUser;
    if (user == null) throw StateError('Sign in required');
    final stamp = DateTime.now().millisecondsSinceEpoch;
    final attachment = await backend.uploadSupportAttachment(
      threadId: threadId,
      bytes: clip.bytes,
      fileName: 'voice_$stamp.wav',
      mimeType: 'audio/wav',
    );
    await backend.client.from('support_messages').insert({
      'thread_id': threadId,
      'sender_id': user.id,
      'sender_role': senderRole,
      'message_type': 'audio',
      'attachment_path': attachment['path'],
      'attachment_name': attachment['name'],
      'attachment_mime': attachment['mime'],
      'attachment_size_bytes': attachment['size'],
      'metadata': {'duration_ms': clip.duration.inMilliseconds},
    });
    await backend.client.from('support_threads').update({
      'status': 'open',
      'updated_at': DateTime.now().toUtc().toIso8601String(),
    }).eq('id', threadId);
  }
}

class VetSupportVoiceNote extends StatefulWidget {
  const VetSupportVoiceNote({super.key, required this.row, required this.mine});
  final Map<String, dynamic> row;
  final bool mine;

  @override
  State<VetSupportVoiceNote> createState() => _VetSupportVoiceNoteState();
}

class _VetSupportVoiceNoteState extends State<VetSupportVoiceNote> {
  final AudioPlayer player = AudioPlayer();
  Uint8List? bytes;
  bool loading = false;
  bool playing = false;
  Duration position = Duration.zero;
  Duration total = Duration.zero;
  StreamSubscription<void>? completeSub;
  StreamSubscription<Duration>? positionSub;
  StreamSubscription<Duration>? durationSub;

  static const pattern = <double>[8, 15, 10, 20, 12, 17, 7, 23, 13, 18, 9, 25, 11, 16, 7, 21, 12, 18, 10, 24, 8, 15, 19, 11, 22, 9, 17, 13, 20, 8, 16, 23];

  @override
  void initState() {
    super.initState();
    total = Duration(milliseconds: durationMs);
    positionSub = player.onPositionChanged.listen((value) {
      if (mounted) setState(() => position = value);
    });
    durationSub = player.onDurationChanged.listen((value) {
      if (mounted && value.inMilliseconds > 0) setState(() => total = value);
    });
    completeSub = player.onPlayerComplete.listen((_) {
      if (mounted) setState(() {
        playing = false;
        position = Duration.zero;
      });
    });
  }

  int get durationMs {
    final meta = widget.row['metadata'];
    if (meta is Map && meta['duration_ms'] is num) {
      return (meta['duration_ms'] as num).toInt();
    }
    return 0;
  }

  String _durationLabel(Duration value) {
    final seconds = value.inSeconds.clamp(0, 3599);
    final m = seconds ~/ 60;
    final s = seconds % 60;
    return '$m:${s.toString().padLeft(2, '0')}';
  }

  double get progress {
    if (total.inMilliseconds <= 0) return 0;
    return (position.inMilliseconds / total.inMilliseconds).clamp(0.0, 1.0).toDouble();
  }

  Future<void> toggle() async {
    if (loading) return;
    if (playing) {
      await player.pause();
      if (mounted) setState(() => playing = false);
      return;
    }
    setState(() => loading = true);
    try {
      bytes ??= await VetBackend.instance.downloadSupportAttachment('${widget.row['attachment_path']}');
      if (position.inMilliseconds > 0 && total.inMilliseconds > 0 && position >= total) {
        position = Duration.zero;
      }
      await player.play(BytesSource(bytes!), position: position);
      if (mounted) setState(() => playing = true);
    } catch (_) {
      if (mounted) setState(() => playing = false);
    } finally {
      if (mounted) setState(() => loading = false);
    }
  }

  Future<void> seek(double fraction) async {
    if (total.inMilliseconds <= 0) return;
    final target = Duration(milliseconds: (total.inMilliseconds * fraction.clamp(0.0, 1.0)).round());
    try {
      await player.seek(target);
      if (mounted) setState(() => position = target);
    } catch (_) {}
  }

  @override
  void dispose() {
    completeSub?.cancel();
    positionSub?.cancel();
    durationSub?.cancel();
    unawaited(player.dispose());
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    const green = Color(0xFF00A884);
    const muted = Color(0xFF667781);
    return SizedBox(
      width: 260,
      child: Row(
        children: [
          InkWell(
            onTap: toggle,
            customBorder: const CircleBorder(),
            child: CircleAvatar(
              radius: 21,
              backgroundColor: green,
              child: loading
                  ? const SizedBox.square(dimension: 17, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white))
                  : Icon(playing ? Icons.pause_rounded : Icons.play_arrow_rounded, color: Colors.white, size: 28),
            ),
          ),
          const SizedBox(width: 9),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.min,
              children: [
                GestureDetector(
                  behavior: HitTestBehavior.opaque,
                  onTapDown: (details) {
                    final box = context.findRenderObject() as RenderBox?;
                    if (box == null) return;
                    final x = details.localPosition.dx - 51;
                    final width = box.size.width - 67;
                    if (width > 0) unawaited(seek(x / width));
                  },
                  child: SizedBox(
                    height: 29,
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        for (var i = 0; i < pattern.length; i++)
                          Expanded(
                            child: Align(
                              child: Container(
                                margin: const EdgeInsets.symmetric(horizontal: .7),
                                height: pattern[i],
                                decoration: BoxDecoration(
                                  color: i / pattern.length <= progress ? green : muted.withValues(alpha: .55),
                                  borderRadius: BorderRadius.circular(3),
                                ),
                              ),
                            ),
                          ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 1),
                Text(
                  playing || position.inMilliseconds > 0 ? _durationLabel(position) : _durationLabel(total),
                  style: const TextStyle(fontSize: 10.5, color: muted),
                ),
              ],
            ),
          ),
          const SizedBox(width: 7),
          Icon(Icons.mic_rounded, size: 18, color: widget.mine ? green : muted),
        ],
      ),
    );
  }
}
''', encoding='utf-8')


# ---------------------------------------------------------------------------
# 3) Live recording bar driven by actual microphone amplitude.
# ---------------------------------------------------------------------------
Path('lib/support/support_voice_recorder_bar.dart').write_text(r'''import 'package:flutter/material.dart';

class VetSupportVoiceRecorderBar extends StatefulWidget {
  const VetSupportVoiceRecorderBar({
    super.key,
    required this.seconds,
    required this.paused,
    required this.busy,
    required this.level,
    required this.onCancel,
    required this.onPauseResume,
    required this.onSend,
  });

  final int seconds;
  final bool paused;
  final bool busy;
  final ValueListenable<double> level;
  final VoidCallback onCancel;
  final VoidCallback onPauseResume;
  final VoidCallback onSend;

  @override
  State<VetSupportVoiceRecorderBar> createState() => _VetSupportVoiceRecorderBarState();
}

class _VetSupportVoiceRecorderBarState extends State<VetSupportVoiceRecorderBar> {
  final List<double> history = List<double>.filled(34, .06);

  @override
  void initState() {
    super.initState();
    widget.level.addListener(_onLevel);
  }

  @override
  void didUpdateWidget(covariant VetSupportVoiceRecorderBar oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.level != widget.level) {
      oldWidget.level.removeListener(_onLevel);
      widget.level.addListener(_onLevel);
    }
  }

  void _onLevel() {
    if (!mounted || widget.paused) return;
    final value = widget.level.value.clamp(0.0, 1.0).toDouble();
    setState(() {
      history.removeAt(0);
      history.add(value < .035 ? .035 : value);
    });
  }

  @override
  void dispose() {
    widget.level.removeListener(_onLevel);
    super.dispose();
  }

  String get timeLabel {
    final m = widget.seconds ~/ 60;
    final s = widget.seconds % 60;
    return '$m:${s.toString().padLeft(2, '0')}';
  }

  @override
  Widget build(BuildContext context) {
    const green = Color(0xFF00A884);
    const red = Color(0xFFE53935);
    const muted = Color(0xFF667781);
    return Container(
      height: 56,
      decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(28)),
      child: Row(
        children: [
          IconButton(
            tooltip: 'Delete recording',
            onPressed: widget.busy ? null : widget.onCancel,
            icon: const Icon(Icons.delete_outline_rounded, color: muted, size: 26),
          ),
          Text(timeLabel, style: const TextStyle(fontSize: 13.5, color: Color(0xFF3B4A54), fontWeight: FontWeight.w600)),
          const SizedBox(width: 8),
          Expanded(
            child: SizedBox(
              height: 30,
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: [
                  for (final value in history)
                    Expanded(
                      child: Align(
                        child: AnimatedContainer(
                          duration: const Duration(milliseconds: 80),
                          margin: const EdgeInsets.symmetric(horizontal: .6),
                          height: 3 + value * 25,
                          decoration: BoxDecoration(
                            color: widget.paused ? muted.withValues(alpha: .35) : muted.withValues(alpha: .72),
                            borderRadius: BorderRadius.circular(3),
                          ),
                        ),
                      ),
                    ),
                ],
              ),
            ),
          ),
          const SizedBox(width: 4),
          ValueListenableBuilder<double>(
            valueListenable: widget.level,
            builder: (context, level, _) => Container(
              width: 22,
              height: 22,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                color: red.withValues(alpha: widget.paused ? .08 : (.10 + level.clamp(0.0, 1.0) * .22)),
              ),
              child: const Icon(Icons.mic_rounded, color: red, size: 17),
            ),
          ),
          const SizedBox(width: 4),
          InkWell(
            onTap: widget.busy ? null : widget.onPauseResume,
            customBorder: const CircleBorder(),
            child: CircleAvatar(
              radius: 19,
              backgroundColor: const Color(0xFFFFE8E8),
              child: Icon(widget.paused ? Icons.play_arrow_rounded : Icons.pause_rounded, color: red, size: 24),
            ),
          ),
          const SizedBox(width: 6),
          InkWell(
            onTap: widget.busy ? null : widget.onSend,
            customBorder: const CircleBorder(),
            child: CircleAvatar(
              radius: 22,
              backgroundColor: green,
              child: widget.busy
                  ? const SizedBox.square(dimension: 18, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white))
                  : const Icon(Icons.send_rounded, color: Colors.white, size: 24),
            ),
          ),
          const SizedBox(width: 4),
        ],
      ),
    );
  }
}
''', encoding='utf-8')


# ---------------------------------------------------------------------------
# 4) Wire the live level into both recording composers.
# ---------------------------------------------------------------------------
for file_path in ['lib/support/support_chat_v6.dart', 'lib/support/support_agent_thread_v2.dart']:
    p = Path(file_path)
    s = p.read_text(encoding='utf-8')
    old = """                          busy: sending,
                          onCancel:""" if file_path.endswith('support_chat_v6.dart') else """                      busy: sending,
                      onCancel:"""
    new = """                          busy: sending,
                          level: voiceRecorder.level,
                          onCancel:""" if file_path.endswith('support_chat_v6.dart') else """                      busy: sending,
                      level: voiceRecorder.level,
                      onCancel:"""
    if 'level: voiceRecorder.level' not in s:
      s = replace_once(s, old, new, f'{file_path} live recorder level')
    p.write_text(s, encoding='utf-8')


# ---------------------------------------------------------------------------
# 5) Robust audio detection. Old deployed rows and browser upload metadata can
#    still vary, so audio is recognized by MIME, message_type OR .wav filename.
# ---------------------------------------------------------------------------
p = Path('lib/support/support_chat_v6.dart')
s = p.read_text(encoding='utf-8')
old = "    final isAudio = path != null && mime.startsWith('audio/');\n"
new = "    final isAudio = path != null && (mime.startsWith('audio/') || '${row['message_type'] ?? ''}' == 'audio' || name.toLowerCase().endsWith('.wav'));\n"
s = replace_once(s, old, new, 'customer robust audio detection')
p.write_text(s, encoding='utf-8')

p = Path('lib/support/support_agent_thread_v2.dart')
s = p.read_text(encoding='utf-8')
old = "    final audio = mime.startsWith('audio/');\n"
new = "    final audio = mime.startsWith('audio/') || '${widget.row['message_type'] ?? ''}' == 'audio' || '${widget.row['attachment_name'] ?? ''}'.toLowerCase().endsWith('.wav');\n"
s = replace_once(s, old, new, 'agent robust audio detection')
p.write_text(s, encoding='utf-8')


checks = {
    'lib/support/support_chat_sound.dart': ['BytesSource(_sendBytes)', 'BytesSource(_receiveBytes)', '_tone(', 'volume: .92', 'volume: .90'],
    'lib/support/support_voice_note.dart': ['ValueNotifier<double> level', '_updateLevel(', 'onPositionChanged', 'onDurationChanged', 'VetSupportVoiceNote extends StatefulWidget'],
    'lib/support/support_voice_recorder_bar.dart': ['ValueListenable<double> level', 'history.removeAt(0)', 'ValueListenableBuilder<double>', 'Icons.pause_rounded', 'Icons.send_rounded'],
    'lib/support/support_chat_v6.dart': ['level: voiceRecorder.level', "message_type'] ?? ''}' == 'audio'", 'VetSupportVoiceNote(row: row, mine: mine)'],
    'lib/support/support_agent_thread_v2.dart': ['level: voiceRecorder.level', "message_type'] ?? ''}' == 'audio'", 'VetSupportVoiceNote('],
}
for path, markers in checks.items():
    text = Path(path).read_text(encoding='utf-8')
    for marker in markers:
        if marker not in text:
            raise SystemExit(f'V73 verification missing: {path} / {marker}')

print('Vet AI V73 applied: playable voice bubbles, live mic waveform and in-memory chat send/receive cues')
