from pathlib import Path

REPORT = Path('lib/analysis/vet_analysis_report.dart')
text = REPORT.read_text(encoding='utf-8')

# This patch runs after patch_v40_voice_pipeline.py. It starts synthesizing the
# first spoken chunk as soon as the report widget exists, while the speaker is
# still OFF. When the user taps the speaker, the already-generated bytes are
# played immediately instead of starting a fresh network TTS request.

if "import 'dart:typed_data';" not in text:
    text = text.replace("import 'dart:io';\n", "import 'dart:io';\nimport 'dart:typed_data';\n", 1)

field_marker = '  int _speechRequestId = 0;\n'
fields = """  Future<Uint8List?>? _voicePrewarmFuture;
  Uint8List? _voicePrewarmBytes;
  String? _voicePrewarmKey;
"""
if '_voicePrewarmFuture' not in text:
    if field_marker not in text:
        raise SystemExit('0.6.24 instant voice: speech request field not found')
    text = text.replace(field_marker, field_marker + fields, 1)

# Start prewarming before the first frame is shown, rather than waiting for the
# user to tap the speaker.
init_old = """    _syncQuestions();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      unawaited(_configureSpeechAudioSession());
    });
"""
init_new = """    _syncQuestions();
    unawaited(_prewarmCurrentVoice());
    WidgetsBinding.instance.addPostFrameCallback((_) {
      unawaited(_configureSpeechAudioSession());
    });
"""
if init_old in text:
    text = text.replace(init_old, init_new, 1)
elif 'unawaited(_prewarmCurrentVoice());' not in text:
    raise SystemExit('0.6.24 instant voice: initState prewarm marker not found')

update_old = """      _result = Map<String, dynamic>.from(widget.initialResult);
      _syncQuestions();
      WidgetsBinding.instance.addPostFrameCallback((_) {
        unawaited(_configureSpeechAudioSession());
      });
"""
update_new = """      _result = Map<String, dynamic>.from(widget.initialResult);
      _syncQuestions();
      _voicePrewarmFuture = null;
      _voicePrewarmBytes = null;
      _voicePrewarmKey = null;
      unawaited(_prewarmCurrentVoice());
      WidgetsBinding.instance.addPostFrameCallback((_) {
        unawaited(_configureSpeechAudioSession());
      });
"""
if update_old in text:
    text = text.replace(update_old, update_new, 1)

# Insert helpers after _splitVoiceChunks and before _playVoiceBytes.
play_marker = '  Future<void> _playVoiceBytes(List<int> natural, int requestId, int index) async {'
if '_preparedVoiceChunks()' not in text:
    idx = text.find(play_marker)
    if idx < 0:
        raise SystemExit('0.6.24 instant voice: play marker not found')
    helpers = r'''  List<String> _preparedVoiceChunks() {
    var text = _buildSpokenReportText();
    if (widget.languageCode.toLowerCase().startsWith('ar')) {
      text = _egyptianSpeechText(text);
    }
    text = _speechSafeText(text);
    // Keep the first request short. Shorter synthesis reaches the phone sooner,
    // while the following chunk is prepared during playback.
    return _splitVoiceChunks(text, maxChars: 300);
  }

  String _voicePrewarmCacheKey(List<String> chunks) {
    if (chunks.isEmpty) return '';
    return '${widget.assessmentId}|${widget.languageCode}|${_result['code']}|${chunks.first}';
  }

  Future<void> _prewarmCurrentVoice() async {
    if (!mounted) return;
    final chunks = _preparedVoiceChunks();
    if (chunks.isEmpty) return;
    final key = _voicePrewarmCacheKey(chunks);
    if (_voicePrewarmKey == key &&
        (_voicePrewarmBytes != null || _voicePrewarmFuture != null)) {
      return;
    }

    _voicePrewarmKey = key;
    _voicePrewarmBytes = null;
    final future = VetBackend.instance.naturalCaseVoice(
      text: chunks.first,
      language: widget.languageCode,
    );
    _voicePrewarmFuture = future;
    try {
      final bytes = await future;
      if (!mounted || _voicePrewarmKey != key) return;
      if (bytes != null && bytes.isNotEmpty) {
        _voicePrewarmBytes = bytes;
        await VetBackend.instance.logVoiceClientEvent(
          stage: 'voice_prewarm_ready',
          route: 'instant_voice_cache',
          detail: 'audio_bytes=${bytes.length}; first_chunk_chars=${chunks.first.length}',
          appVersion: '0.6.24',
        );
      }
    } catch (e) {
      if (_voicePrewarmKey == key) {
        _voicePrewarmFuture = null;
      }
      try {
        await VetBackend.instance.logVoiceClientEvent(
          stage: 'voice_prewarm_error',
          route: 'instant_voice_cache',
          detail: e.toString(),
          appVersion: '0.6.24',
        );
      } catch (_) {}
    }
  }

'''
    text = text[:idx] + helpers + text[idx:]

# Replace the v40 text preparation with the common prewarmed chunk builder.
old_prepare = """    var text = _buildSpokenReportText();
    if (widget.languageCode.toLowerCase().startsWith('ar')) {
      text = _egyptianSpeechText(text);
    }
    text = _speechSafeText(text);
    final chunks = _splitVoiceChunks(text);
"""
new_prepare = """    final chunks = _preparedVoiceChunks();
"""
if old_prepare in text:
    text = text.replace(old_prepare, new_prepare, 1)
elif 'final chunks = _preparedVoiceChunks();' not in text:
    raise SystemExit('0.6.24 instant voice: v40 chunk preparation block not found')

# Use the prewarmed first chunk if available. If synthesis is still in flight,
# reuse that same Future instead of launching a duplicate request.
old_pending = """      var pending = VetBackend.instance.naturalCaseVoice(
        text: chunks.first,
        language: widget.languageCode,
      );

      for (var i = 0; i < chunks.length; i++) {
"""
new_pending = """      final cacheKey = _voicePrewarmCacheKey(chunks);
      Future<Uint8List?> pending;
      if (_voicePrewarmKey == cacheKey && _voicePrewarmBytes != null) {
        pending = Future<Uint8List?>.value(_voicePrewarmBytes);
        unawaited(VetBackend.instance.logVoiceClientEvent(
          stage: 'voice_tap_cache_hit',
          route: 'instant_voice_cache',
          detail: 'first_chunk_chars=${chunks.first.length}',
          appVersion: '0.6.24',
        ));
      } else if (_voicePrewarmKey == cacheKey && _voicePrewarmFuture != null) {
        pending = _voicePrewarmFuture!;
        unawaited(VetBackend.instance.logVoiceClientEvent(
          stage: 'voice_tap_waiting_for_prewarm',
          route: 'instant_voice_cache',
          detail: 'first_chunk_chars=${chunks.first.length}',
          appVersion: '0.6.24',
        ));
      } else {
        pending = VetBackend.instance.naturalCaseVoice(
          text: chunks.first,
          language: widget.languageCode,
        );
      }

      for (var i = 0; i < chunks.length; i++) {
"""
if old_pending in text:
    text = text.replace(old_pending, new_pending, 1)
elif 'voice_tap_cache_hit' not in text:
    raise SystemExit('0.6.24 instant voice: v40 pending block not found')

REPORT.write_text(text, encoding='utf-8')

check = REPORT.read_text(encoding='utf-8')
required = (
    '_voicePrewarmFuture',
    '_voicePrewarmBytes',
    '_prewarmCurrentVoice()',
    '_preparedVoiceChunks()',
    'voice_prewarm_ready',
    'voice_tap_cache_hit',
    'instant_voice_cache',
    'maxChars: 300',
)
for marker in required:
    if marker not in check:
        raise SystemExit(f'0.6.24 instant voice verification missing: {marker}')

print('Vet AI 0.6.24 instant-on-tap voice prewarm cache installed')
