-- Vet AI core backend schema
-- Run this in Supabase SQL Editor for the Vet AI Backend project.

create extension if not exists pgcrypto;

create type public.member_role as enum ('owner', 'manager', 'veterinarian', 'supervisor', 'worker');
create type public.animal_group as enum ('livestock', 'poultry', 'dogs');
create type public.risk_level as enum ('none', 'yellow', 'orange', 'red', 'insufficient_data');
create type public.assessment_status as enum ('draft', 'ai_review', 'vet_reviewed', 'lab_confirmed');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  preferred_language text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.farms (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  company_name text,
  farm_name text not null,
  country text,
  region text,
  worker_count integer not null default 0 check (worker_count >= 0),
  veterinarian_count integer not null default 0 check (veterinarian_count >= 0),
  total_indoor_area_m2 numeric check (total_indoor_area_m2 >= 0),
  production_purpose text,
  ventilation_system text,
  vaccination_notes text,
  disease_history text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.farm_members (
  farm_id uuid not null references public.farms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.member_role not null default 'worker',
  created_at timestamptz not null default now(),
  primary key (farm_id, user_id)
);

create table public.barns (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid not null references public.farms(id) on delete cascade,
  name text not null,
  animal_group public.animal_group not null,
  indoor_area_m2 numeric check (indoor_area_m2 >= 0),
  capacity integer check (capacity >= 0),
  notes text,
  created_at timestamptz not null default now()
);

create table public.animals (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid not null references public.farms(id) on delete cascade,
  barn_id uuid references public.barns(id) on delete set null,
  animal_group public.animal_group not null,
  external_id text,
  name text,
  species text,
  breed text,
  sex text,
  birth_date date,
  approximate_age_days integer check (approximate_age_days >= 0),
  weight_kg numeric check (weight_kg >= 0),
  pregnant boolean,
  expected_calving_date date,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (farm_id, external_id)
);

create table public.flocks (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid not null references public.farms(id) on delete cascade,
  barn_id uuid references public.barns(id) on delete set null,
  animal_group public.animal_group not null,
  name text not null,
  species text,
  breed_or_strain text,
  head_count integer not null default 0 check (head_count >= 0),
  age_days integer check (age_days >= 0),
  production_cycle text,
  created_at timestamptz not null default now()
);

create table public.assessments (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid not null references public.farms(id) on delete cascade,
  animal_id uuid references public.animals(id) on delete set null,
  flock_id uuid references public.flocks(id) on delete set null,
  created_by uuid not null references auth.users(id) on delete restrict,
  media_path text,
  symptom_notes text,
  observed_signs jsonb not null default '[]'::jsonb,
  differential_diagnoses jsonb not null default '[]'::jsonb,
  risk public.risk_level not null default 'insufficient_data',
  isolation_recommended boolean,
  urgent_vet_review boolean,
  lab_confirmation_required boolean,
  status public.assessment_status not null default 'draft',
  veterinarian_notes text,
  laboratory_result text,
  created_at timestamptz not null default now()
);

create table public.sensor_devices (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid not null references public.farms(id) on delete cascade,
  animal_id uuid references public.animals(id) on delete set null,
  barn_id uuid references public.barns(id) on delete set null,
  device_uid text not null unique,
  device_type text not null,
  firmware_version text,
  last_seen_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.sensor_readings (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.sensor_devices(id) on delete cascade,
  farm_id uuid not null references public.farms(id) on delete cascade,
  animal_id uuid references public.animals(id) on delete set null,
  recorded_at timestamptz not null,
  body_temperature_c numeric,
  ambient_temperature_c numeric,
  humidity_percent numeric,
  activity_index numeric,
  steps integer,
  distance_from_herd_m numeric,
  lying_minutes numeric,
  feeding_minutes numeric,
  rumination_minutes numeric,
  gps_lat numeric,
  gps_lon numeric,
  raw jsonb not null default '{}'::jsonb
);

create index sensor_readings_farm_time_idx on public.sensor_readings (farm_id, recorded_at desc);
create index sensor_readings_animal_time_idx on public.sensor_readings (animal_id, recorded_at desc);

create table public.alerts (
  id uuid primary key default gen_random_uuid(),
  farm_id uuid not null references public.farms(id) on delete cascade,
  animal_id uuid references public.animals(id) on delete set null,
  flock_id uuid references public.flocks(id) on delete set null,
  assessment_id uuid references public.assessments(id) on delete set null,
  risk public.risk_level not null,
  title text not null,
  details text,
  acknowledged_at timestamptz,
  acknowledged_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger farms_set_updated_at
before update on public.farms
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, phone, preferred_language)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    new.raw_user_meta_data ->> 'phone',
    new.raw_user_meta_data ->> 'preferred_language'
  );
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_farm_member(target_farm uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.farms f
    where f.id = target_farm and f.owner_id = auth.uid()
  ) or exists (
    select 1
    from public.farm_members fm
    where fm.farm_id = target_farm and fm.user_id = auth.uid()
  );
$$;

alter table public.profiles enable row level security;
alter table public.farms enable row level security;
alter table public.farm_members enable row level security;
alter table public.barns enable row level security;
alter table public.animals enable row level security;
alter table public.flocks enable row level security;
alter table public.assessments enable row level security;
alter table public.sensor_devices enable row level security;
alter table public.sensor_readings enable row level security;
alter table public.alerts enable row level security;

create policy profiles_self_select on public.profiles
for select using (id = auth.uid());
create policy profiles_self_update on public.profiles
for update using (id = auth.uid()) with check (id = auth.uid());

create policy farms_member_select on public.farms
for select using (public.is_farm_member(id));
create policy farms_owner_insert on public.farms
for insert with check (owner_id = auth.uid());
create policy farms_owner_update on public.farms
for update using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy farms_owner_delete on public.farms
for delete using (owner_id = auth.uid());

create policy farm_members_member_select on public.farm_members
for select using (public.is_farm_member(farm_id));
create policy farm_members_owner_manage on public.farm_members
for all using (
  exists (select 1 from public.farms f where f.id = farm_id and f.owner_id = auth.uid())
) with check (
  exists (select 1 from public.farms f where f.id = farm_id and f.owner_id = auth.uid())
);

create policy barns_member_all on public.barns
for all using (public.is_farm_member(farm_id)) with check (public.is_farm_member(farm_id));
create policy animals_member_all on public.animals
for all using (public.is_farm_member(farm_id)) with check (public.is_farm_member(farm_id));
create policy flocks_member_all on public.flocks
for all using (public.is_farm_member(farm_id)) with check (public.is_farm_member(farm_id));
create policy assessments_member_all on public.assessments
for all using (public.is_farm_member(farm_id)) with check (public.is_farm_member(farm_id));
create policy sensor_devices_member_all on public.sensor_devices
for all using (public.is_farm_member(farm_id)) with check (public.is_farm_member(farm_id));
create policy sensor_readings_member_select on public.sensor_readings
for select using (public.is_farm_member(farm_id));
create policy alerts_member_all on public.alerts
for all using (public.is_farm_member(farm_id)) with check (public.is_farm_member(farm_id));

insert into storage.buckets (id, name, public)
values ('diagnostic-media', 'diagnostic-media', false)
on conflict (id) do nothing;

create policy diagnostic_media_owner_insert on storage.objects
for insert to authenticated
with check (
  bucket_id = 'diagnostic-media'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy diagnostic_media_owner_select on storage.objects
for select to authenticated
using (
  bucket_id = 'diagnostic-media'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy diagnostic_media_owner_update on storage.objects
for update to authenticated
using (
  bucket_id = 'diagnostic-media'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'diagnostic-media'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy diagnostic_media_owner_delete on storage.objects
for delete to authenticated
using (
  bucket_id = 'diagnostic-media'
  and (storage.foldername(name))[1] = auth.uid()::text
);
