-- Curated, source-backed disease knowledge for Vet AI.
-- This is intentionally not an exhaustive disease catalogue. Add conditions only after veterinary/source review.

create table if not exists public.disease_catalog (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  display_name text not null,
  animal_groups public.animal_group[] not null,
  agent_type text not null,
  cause text,
  zoonotic boolean not null default false,
  reportable_or_listed boolean not null default false,
  default_risk public.risk_level not null default 'yellow',
  isolation_guidance text,
  lab_confirmation_required boolean not null default true,
  source_org text not null,
  source_url text not null,
  source_reviewed_at date,
  curated_at timestamptz not null default now()
);

create table if not exists public.disease_signs (
  id bigint generated by default as identity primary key,
  disease_id uuid not null references public.disease_catalog(id) on delete cascade,
  phase text not null check (phase in ('early','clinical','severe')),
  sign text not null,
  visible_in_image boolean not null default false,
  visible_in_video boolean not null default false,
  sensor_detectable boolean not null default false,
  source_url text not null,
  unique(disease_id, phase, sign)
);

alter table public.disease_catalog enable row level security;
alter table public.disease_signs enable row level security;

grant select on public.disease_catalog, public.disease_signs to authenticated;
grant usage, select on sequence public.disease_signs_id_seq to authenticated;

create policy disease_catalog_authenticated_read on public.disease_catalog
for select to authenticated using (true);
create policy disease_signs_authenticated_read on public.disease_signs
for select to authenticated using (true);

-- Initial high-priority viral conditions. Source URLs are authoritative veterinary references.
insert into public.disease_catalog
(slug, display_name, animal_groups, agent_type, cause, zoonotic, reportable_or_listed, default_risk, isolation_guidance, lab_confirmation_required, source_org, source_url, source_reviewed_at)
values
('fmd','Foot-and-mouth disease',array['livestock']::public.animal_group[],'virus','Foot-and-mouth disease virus',false,true,'red','Immediately separate suspected cloven-hoofed animals from unaffected stock, stop animal movement, and contact a veterinarian and the competent animal-health authority.',true,'WOAH','https://www.woah.org/en/disease/foot-and-mouth-disease/','2026-09-04'),
('ppr','Peste des petits ruminants',array['livestock']::public.animal_group[],'virus','Morbillivirus affecting primarily sheep and goats',false,true,'red','Separate suspected sheep/goats, reduce movement and shared equipment, and obtain urgent veterinary/official guidance.',true,'WOAH','https://www.woah.org/en/disease/peste-des-petits-ruminants/','2026-09-04'),
('newcastle','Newcastle disease',array['poultry']::public.animal_group[],'virus','Virulent Newcastle disease virus',false,true,'red','Isolate the affected flock, stop movement of birds/equipment, strengthen biosecurity, and seek urgent veterinary and official guidance.',true,'WOAH','https://www.woah.org/en/disease/newcastle-disease/','2026-09-04'),
('avian-influenza','Avian influenza',array['poultry']::public.animal_group[],'virus','Influenza A viruses; high-pathogenicity strains can cause severe disease',true,true,'red','Do not move suspect birds. Isolate the flock, restrict access, use appropriate PPE and contact veterinary/public animal-health authorities.',true,'WOAH','https://www.woah.org/en/disease/avian-influenza/','2026-09-04'),
('canine-parvovirus','Canine parvovirus infection',array['dogs']::public.animal_group[],'virus','Canine parvovirus',false,false,'orange','Separate the dog from susceptible dogs and obtain prompt veterinary assessment because dehydration and systemic complications can progress rapidly.',true,'Merck Veterinary Manual','https://www.merckvetmanual.com/digestive-system/infectious-diseases-of-the-gastrointestinal-tract-in-small-animals/canine-parvovirus-infection-parvoviral-enteritis-in-dogs','2026-09-04'),
('canine-distemper','Canine distemper',array['dogs']::public.animal_group[],'virus','Canine distemper virus',false,false,'orange','Separate the dog from other susceptible dogs and seek veterinary assessment; respiratory, gastrointestinal and neurological signs can evolve over time.',true,'Merck Veterinary Manual','https://www.merckvetmanual.com/infectious-diseases/canine-distemper/canine-distemper','2026-09-04'),
('rabies','Rabies',array['livestock','dogs']::public.animal_group[],'virus','Rabies virus affecting the central nervous system of mammals',true,true,'red','Avoid direct contact with saliva, safely separate the animal if possible without exposure, and immediately contact veterinary and public-health authorities.',true,'WOAH','https://www.woah.org/en/disease/rabies/','2026-09-04')
on conflict (slug) do nothing;

with d as (select id,slug,source_url from public.disease_catalog)
insert into public.disease_signs(disease_id,phase,sign,visible_in_image,visible_in_video,sensor_detectable,source_url)
select d.id, x.phase, x.sign, x.img, x.vid, x.sensor, d.source_url
from d
join (values
('fmd','early','Fever',false,false,true),
('fmd','clinical','Blister-like sores/vesicles in or around the mouth, tongue or lips',true,false,false),
('fmd','clinical','Vesicles or lesions between the toes or above the hooves',true,false,false),
('fmd','clinical','Hypersalivation',true,true,false),
('fmd','clinical','Lameness or reluctance to move',false,true,true),
('ppr','early','High fever and depression',false,true,true),
('ppr','clinical','Eye and nasal discharge',true,true,false),
('ppr','clinical','Painful erosive oral lesions',true,false,false),
('ppr','clinical','Severe diarrhoea',true,true,false),
('ppr','severe','Severe pneumonia or respiratory distress',false,true,true),
('newcastle','early','Rapid onset illness within flock',false,true,true),
('newcastle','clinical','Gasping, coughing, sneezing or rales',false,true,true),
('newcastle','clinical','Tremors, twisted neck, circling or paralysis',false,true,true),
('newcastle','clinical','Diarrhoea',true,true,false),
('newcastle','severe','Sudden or rapidly escalating flock mortality',false,false,true),
('avian-influenza','early','Apathy and reduced feed or water intake',false,true,true),
('avian-influenza','clinical','Respiratory distress or neurological signs',false,true,true),
('avian-influenza','clinical','Cyanosis of unfeathered skin, wattles or comb',true,false,false),
('avian-influenza','clinical','Marked drop in egg production',false,false,true),
('avian-influenza','severe','High and rapidly escalating unexplained mortality',false,false,true),
('canine-parvovirus','early','Lethargy, anorexia or fever',false,true,true),
('canine-parvovirus','clinical','Vomiting',false,true,false),
('canine-parvovirus','clinical','Acute diarrhoea, often haemorrhagic',true,true,false),
('canine-parvovirus','severe','Dehydration, collapse or signs compatible with shock',false,true,true),
('canine-distemper','early','Fever, lethargy and loss of appetite',false,true,true),
('canine-distemper','clinical','Nasal or ocular discharge',true,true,false),
('canine-distemper','clinical','Respiratory signs or pneumonia',false,true,true),
('canine-distemper','clinical','Diarrhoea',true,true,false),
('canine-distemper','severe','Muscle twitching or seizures',false,true,true),
('rabies','early','Nonspecific lethargy, fever, vomiting or anorexia',false,true,true),
('rabies','clinical','Sudden abnormal behaviour or aggression',false,true,true),
('rabies','clinical','Ataxia, weakness or progressive paralysis',false,true,true),
('rabies','clinical','Difficulty swallowing with excessive salivation',true,true,false),
('rabies','severe','Seizures or respiratory difficulty',false,true,true)
) as x(slug,phase,sign,img,vid,sensor) on x.slug=d.slug
on conflict (disease_id,phase,sign) do nothing;
