-- Vet AI V30: global veterinary knowledge provenance + deterministic safety guardrails.

create table if not exists public.disease_source_refs (
  id uuid primary key default gen_random_uuid(),
  disease_id uuid not null references public.disease_catalog(id) on delete cascade,
  source_org text not null,
  jurisdiction text not null default 'global',
  source_title text,
  source_url text not null,
  evidence_scope text[] not null default '{}',
  source_reviewed_at date,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (disease_id, source_url)
);
alter table public.disease_source_refs enable row level security;
drop policy if exists "authenticated can read disease source refs" on public.disease_source_refs;
create policy "authenticated can read disease source refs" on public.disease_source_refs for select to authenticated using (true);
grant select on public.disease_source_refs to authenticated;

create table if not exists public.disease_aliases (
  id bigint generated by default as identity primary key,
  disease_id uuid not null references public.disease_catalog(id) on delete cascade,
  alias text not null,
  language_code text not null default 'en',
  source_org text,
  source_url text,
  created_at timestamptz not null default now(),
  unique (disease_id, alias, language_code)
);
alter table public.disease_aliases enable row level security;
drop policy if exists "authenticated can read disease aliases" on public.disease_aliases;
create policy "authenticated can read disease aliases" on public.disease_aliases for select to authenticated using (true);
grant select on public.disease_aliases to authenticated;

create table if not exists public.knowledge_sync_runs (
  id uuid primary key default gen_random_uuid(),
  source_org text not null,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  status text not null default 'running' check (status in ('running','success','partial','failed')),
  indexed_count integer not null default 0,
  reviewed_count integer not null default 0,
  error_summary text
);
alter table public.knowledge_sync_runs enable row level security;

create table if not exists public.voice_provider_events (
  id bigint generated by default as identity primary key,
  user_id uuid,
  requested_language text,
  provider text not null,
  model_or_voice text,
  outcome text not null check (outcome in ('success','failure','timeout','not_configured')),
  http_status integer,
  detail text,
  created_at timestamptz not null default now()
);
alter table public.voice_provider_events enable row level security;
create index if not exists voice_provider_events_created_at_idx on public.voice_provider_events(created_at desc);

create or replace function public.vet_ai_guard_assessment_output()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  morphology text;
  species text;
  salivation boolean;
  foot_lesions boolean;
  fmd_strong boolean;
  diffs jsonb;
  guarded jsonb;
  has_orf boolean;
  is_small_ruminant boolean;
  final_primary_slug text;
  final_provider text;
begin
  if new.status = 'ai_review' then
    morphology := coalesce(new.ai_analysis->>'lesion_morphology', 'uncertain');
    species := lower(coalesce(new.ai_analysis->>'species_observed', ''));
    salivation := coalesce((new.ai_analysis->>'visible_hypersalivation')::boolean, false);
    foot_lesions := coalesce((new.ai_analysis->>'visible_foot_lesions')::boolean, false);
    fmd_strong := morphology in ('vesicles_erosions','mixed') and (salivation or foot_lesions);
    is_small_ruminant := species ~ '(sheep|goat|lamb|kid|ovine|caprine|غنم|خروف|ماعز|جدي|حمل)';
    diffs := coalesce(new.differential_diagnoses, '[]'::jsonb);
    has_orf := exists (select 1 from jsonb_array_elements(diffs) x where x->>'catalog_slug' = 'orf');

    select coalesce(jsonb_agg(item order by rank desc, ord), '[]'::jsonb) into guarded
    from (
      select
        case
          when x->>'catalog_slug' = 'fmd' and not fmd_strong then
            jsonb_set(
              jsonb_set(x,'{suspicion}',to_jsonb(case when morphology in ('vesicles_erosions','mixed') then 'moderate' else 'low' end),true),
              '{reasoning}',
              to_jsonb(case when morphology='proliferative_crusts'
                then 'FMD remains an important reportable rule-out, but thick proliferative crusts/scabs are not strong image evidence for FMD without true vesicles/erosions plus corroborating hypersalivation or foot lesions.'
                else 'FMD remains an important rule-out, but the image does not show the minimum morphology and corroborating evidence required for high image suspicion.' end),
              true)
          when x->>'catalog_slug'='orf' and is_small_ruminant and morphology='proliferative_crusts'
            then jsonb_set(x,'{suspicion}','"high"'::jsonb,true)
          else x
        end as item,
        case
          when x->>'catalog_slug'='orf' and is_small_ruminant and morphology='proliferative_crusts' then 50
          when x->>'catalog_slug'='fmd' and not fmd_strong then 5
          when x->>'suspicion'='high' then 40
          when x->>'suspicion'='moderate' then 30
          else 20
        end as rank,
        ord
      from jsonb_array_elements(diffs) with ordinality a(x,ord)
    ) ranked;

    new.differential_diagnoses := guarded;
    new.ai_analysis := jsonb_set(new.ai_analysis,'{differential_diagnoses}',guarded,true);

    if is_small_ruminant and morphology='proliferative_crusts' and not has_orf
       and exists(select 1 from public.disease_catalog d where d.slug='orf' and d.curation_status='reviewed') then
      guarded := jsonb_build_array(jsonb_build_object(
        'catalog_slug','orf','name','Orf (contagious ecthyma / sore mouth)','suspicion','high',
        'reasoning','In a sheep/goat, thick proliferative crusts and adherent scabs around the lips or muzzle are substantially more compatible with Orf than with high-image-suspicion FMD when true vesicles and foot lesions are not visible.',
        'default_risk','yellow','lab_confirmation_required',true,'diagnostics_required',true
      )) || guarded;
      new.differential_diagnoses := guarded;
      new.ai_analysis := jsonb_set(new.ai_analysis,'{differential_diagnoses}',guarded,true);
    end if;
  end if;

  if new.status='final_report' then
    final_primary_slug := coalesce(new.ai_analysis#>>'{primary_condition,catalog_slug}','');
    final_provider := lower(coalesce(new.ai_analysis->>'provider',''));
    if final_primary_slug='fmd' and (new.ai_analysis->>'fast_fallback'='true' or final_provider='reviewed-catalog-fallback') then
      morphology := coalesce(old.ai_analysis->>'lesion_morphology','uncertain');
      species := lower(coalesce(old.ai_analysis->>'species_observed',''));
      salivation := coalesce((old.ai_analysis->>'visible_hypersalivation')::boolean,false);
      foot_lesions := coalesce((old.ai_analysis->>'visible_foot_lesions')::boolean,false);
      fmd_strong := morphology in ('vesicles_erosions','mixed') and (salivation or foot_lesions);
      is_small_ruminant := species ~ '(sheep|goat|lamb|kid|ovine|caprine|غنم|خروف|ماعز|جدي|حمل)';
      if not fmd_strong then
        if is_small_ruminant and morphology='proliferative_crusts' and exists(select 1 from jsonb_array_elements(coalesce(old.differential_diagnoses,'[]'::jsonb)) x where x->>'catalog_slug'='orf') then
          new.ai_analysis := jsonb_set(new.ai_analysis,'{primary_condition}',jsonb_build_object(
            'catalog_slug','orf',
            'name',case when coalesce(new.ai_analysis->>'report_language','') like 'ar%' then 'الأورف (التهاب الفم المعدي)' else 'Orf (contagious ecthyma / sore mouth)' end,
            'suspicion','high',
            'why',case when coalesce(new.ai_analysis->>'report_language','') like 'ar%' then 'شكل القشور التكاثرية الملتصقة حول الشفاه أو الخطم في الأغنام أو الماعز يتوافق مع الأورف أكثر من الحمى القلاعية عندما لا تظهر حويصلات حقيقية أو إصابات قدم.' else 'Proliferative adherent crusts around the lips or muzzle of a sheep/goat are more compatible with Orf than FMD when true vesicles or foot lesions are not visible.' end
          ),true);
        else
          new.ai_analysis := jsonb_set(new.ai_analysis,'{primary_condition}',jsonb_build_object(
            'catalog_slug','unconfirmed-oral-skin-lesion',
            'name',case when coalesce(new.ai_analysis->>'report_language','') like 'ar%' then 'آفة فموية/جلدية غير مؤكدة' else 'Unconfirmed oral/skin lesion syndrome' end,
            'suspicion','uncertain',
            'why',case when coalesce(new.ai_analysis->>'report_language','') like 'ar%' then 'الصورة وحدها لا تحتوي على الأدلة الشكلية الكافية لاعتبار الحمى القلاعية التشخيص الأكثر احتمالًا. تظل الحمى القلاعية مرضًا مهمًا يجب استبعاده عند وجود العلامات المناسبة.' else 'The image alone does not contain enough morphology to make FMD the most likely condition. FMD remains an important rule-out when compatible signs are present.' end
          ),true);
        end if;
        new.ai_analysis := jsonb_set(new.ai_analysis,'{voice_summary}',to_jsonb(case when coalesce(new.ai_analysis->>'report_language','') like 'ar%' then 'الحالة غير مؤكدة من الصورة وحدها، وتحتاج مراجعة بيطرية حسب مستوى الخطورة والعلامات المصاحبة.' else 'The condition is not confirmed from the image alone and needs veterinary review according to the risk and accompanying signs.' end),true);
      end if;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_vet_ai_guard_assessment_output on public.assessments;
create trigger trg_vet_ai_guard_assessment_output
before update of differential_diagnoses, ai_analysis, status on public.assessments
for each row execute function public.vet_ai_guard_assessment_output();
