alter table public.assessments add column if not exists species_code text;
alter table public.assessments add column if not exists bird_type text;

alter table public.farms add column if not exists livestock_species text[] not null default '{}'::text[];
alter table public.farms add column if not exists bird_species text[] not null default '{}'::text[];
alter table public.farms add column if not exists dog_enabled boolean not null default false;

alter table public.sensor_devices add column if not exists controller_model text;
alter table public.sensor_devices add column if not exists sensor_models text[] not null default '{}'::text[];
alter table public.sensor_devices add column if not exists battery_capacity_mah integer;
alter table public.sensor_devices add column if not exists power_module text;
alter table public.sensor_devices add column if not exists device_secret_hash text;
alter table public.sensor_devices add column if not exists capabilities jsonb not null default '{}'::jsonb;

alter table public.sensor_readings add column if not exists accel_x_g numeric;
alter table public.sensor_readings add column if not exists accel_y_g numeric;
alter table public.sensor_readings add column if not exists accel_z_g numeric;
alter table public.sensor_readings add column if not exists oxygen_percent numeric;
alter table public.sensor_readings add column if not exists current_amp numeric;
alter table public.sensor_readings add column if not exists battery_voltage_v numeric;
alter table public.sensor_readings add column if not exists battery_percent numeric;
alter table public.sensor_readings add column if not exists charging boolean;

alter table public.sensor_alert_rules add column if not exists unit text;
alter table public.sensor_alert_rules add column if not exists sensor_model text;
alter table public.sensor_alert_rules add column if not exists value_kind text not null default 'direct';
alter table public.sensor_alert_rules add column if not exists comparison_mode text not null default 'outside_range';

create table if not exists public.sensor_hardware_catalog (
  model text primary key,
  category text not null,
  controller text,
  direct_metrics text[] not null default '{}'::text[],
  derived_metrics text[] not null default '{}'::text[],
  notes text,
  created_at timestamptz not null default now()
);

insert into public.sensor_hardware_catalog(model,category,controller,direct_metrics,derived_metrics,notes) values
('ESP32-C3 SuperMini','controller','ESP32-C3 SuperMini',array[]::text[],array[]::text[],'Central controller for collection and transmission.'),
('MPU6050','wearable_motion','ESP32-C3 SuperMini',array['accel_x_g','accel_y_g','accel_z_g'],array['activity_index','steps','lying_minutes','feeding_minutes','rumination_minutes'],'Behavior metrics are derived estimates and require calibration/model validation for mounting position and species.'),
('SHT40','environment','ESP32-C3 SuperMini',array['ambient_temperature_c','humidity_percent'],array[]::text[],'Barn environmental temperature and relative humidity.'),
('SC4-O2','air_quality','ESP32-C3 SuperMini',array['oxygen_percent'],array[]::text[],'Oxygen measurement requires the signal-conditioning/interface specified by the purchased SC4-O2 variant.'),
('SCT-013','power','ESP32-C3 SuperMini',array['current_amp'],array[]::text[],'Current transformer input requires the correct burden/bias interface for the exact SCT-013 variant.'),
('TP4056 + LiPo 3.7V 5000mAh','power','ESP32-C3 SuperMini',array['battery_voltage_v','battery_percent','charging'],array[]::text[],'TP4056 is a charger, not a fuel gauge. Battery percentage requires ADC voltage measurement with suitable divider or a dedicated fuel-gauge IC.')
on conflict (model) do update set category=excluded.category, controller=excluded.controller, direct_metrics=excluded.direct_metrics, derived_metrics=excluded.derived_metrics, notes=excluded.notes;

create table if not exists public.voice_client_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  stage text not null,
  route text,
  http_status integer,
  detail text,
  app_version text,
  project_ref text
);
alter table public.voice_client_events enable row level security;
drop policy if exists voice_client_events_insert_own on public.voice_client_events;
create policy voice_client_events_insert_own on public.voice_client_events for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists voice_client_events_select_own on public.voice_client_events;
create policy voice_client_events_select_own on public.voice_client_events for select to authenticated using (auth.uid() = user_id);

create or replace function public.sensor_metric_value(p public.sensor_readings, metric_name text)
returns numeric language sql immutable as $$
select case metric_name
  when 'ambient_temperature_c' then p.ambient_temperature_c
  when 'humidity_percent' then p.humidity_percent
  when 'oxygen_percent' then p.oxygen_percent
  when 'current_amp' then p.current_amp
  when 'battery_percent' then p.battery_percent
  when 'activity_index' then p.activity_index
  when 'steps' then p.steps::numeric
  when 'lying_minutes' then p.lying_minutes
  when 'feeding_minutes' then p.feeding_minutes
  when 'rumination_minutes' then p.rumination_minutes
  else null
end
$$;

create or replace function public.evaluate_sensor_alert_rules()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  r record;
  v numeric;
  breached boolean;
  threshold_desc text;
begin
  for r in select * from public.sensor_alert_rules where farm_id = new.farm_id and enabled = true loop
    v := public.sensor_metric_value(new, r.metric);
    if v is null then continue; end if;
    breached := (r.min_value is not null and v < r.min_value) or (r.max_value is not null and v > r.max_value);
    if not breached then continue; end if;
    if exists (
      select 1 from public.alerts a
      where a.farm_id = new.farm_id and a.source = 'sensor_rule' and a.metric = r.metric
        and a.created_at > now() - make_interval(mins => greatest(coalesce(r.cooldown_minutes,30),1))
    ) then continue; end if;
    threshold_desc := concat_ws(' / ',
      case when r.min_value is not null then 'min ' || r.min_value::text || coalesce(' '||r.unit,'') end,
      case when r.max_value is not null then 'max ' || r.max_value::text || coalesce(' '||r.unit,'') end
    );
    insert into public.alerts(farm_id,animal_id,risk,title,details,source,metric,sensor_reading_id,value_numeric,threshold_text)
    values(new.farm_id,new.animal_id,r.severity,coalesce(nullif(r.label,''),'Sensor alert: '||r.metric),'Real sensor reading crossed the configured threshold.','sensor_rule',r.metric,new.id,v,threshold_desc);
  end loop;
  return new;
end
$$;

drop trigger if exists trg_evaluate_sensor_alert_rules on public.sensor_readings;
create trigger trg_evaluate_sensor_alert_rules after insert on public.sensor_readings for each row execute function public.evaluate_sensor_alert_rules();

create index if not exists idx_assessments_species_code on public.assessments(species_code);
create index if not exists idx_sensor_readings_farm_recorded on public.sensor_readings(farm_id,recorded_at desc);
create index if not exists idx_sensor_alert_rules_farm_metric on public.sensor_alert_rules(farm_id,metric) where enabled=true;
