create extension if not exists pg_net;

create table if not exists public.push_devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  farm_id uuid not null references public.farms(id) on delete cascade,
  platform text not null default 'ios' check (platform in ('ios')),
  device_token text not null unique,
  environment text not null default 'production' check (environment in ('production','sandbox')),
  enabled boolean not null default true,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_devices_farm_enabled_idx
  on public.push_devices (farm_id, enabled)
  where enabled = true;
create index if not exists push_devices_user_idx
  on public.push_devices (user_id);

alter table public.push_devices enable row level security;
revoke all on public.push_devices from anon, authenticated;
grant all on public.push_devices to service_role;

create table if not exists public.push_deliveries (
  id bigint generated by default as identity primary key,
  alert_id uuid not null references public.alerts(id) on delete cascade,
  push_device_id uuid not null references public.push_devices(id) on delete cascade,
  status text not null default 'sending' check (status in ('sending','sent','failed')),
  apns_id text,
  error text,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  unique (alert_id, push_device_id)
);

create index if not exists push_deliveries_alert_idx on public.push_deliveries (alert_id);
create index if not exists push_deliveries_device_idx on public.push_deliveries (push_device_id, created_at desc);

alter table public.push_deliveries enable row level security;
revoke all on public.push_deliveries from anon, authenticated;
grant all on public.push_deliveries to service_role;

create or replace function public.register_push_device(
  p_farm_id uuid,
  p_device_token text,
  p_environment text default 'production'
) returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := auth.uid();
  v_id uuid;
  v_token text := lower(trim(p_device_token));
  v_environment text := lower(trim(coalesce(p_environment, 'production')));
begin
  if v_user is null then
    raise exception 'Authentication required';
  end if;
  if not private.is_farm_member(p_farm_id) then
    raise exception 'Farm access denied';
  end if;
  if v_token !~ '^[0-9a-f]{64,}$' then
    raise exception 'Invalid APNs device token';
  end if;
  if v_environment not in ('production','sandbox') then
    v_environment := 'production';
  end if;

  insert into public.push_devices(user_id, farm_id, platform, device_token, environment, enabled, last_seen_at, updated_at)
  values(v_user, p_farm_id, 'ios', v_token, v_environment, true, now(), now())
  on conflict (device_token) do update set
    user_id = excluded.user_id,
    farm_id = excluded.farm_id,
    platform = excluded.platform,
    environment = excluded.environment,
    enabled = true,
    last_seen_at = now(),
    updated_at = now()
  returning id into v_id;

  return v_id;
end
$$;

revoke all on function public.register_push_device(uuid,text,text) from public, anon;
grant execute on function public.register_push_device(uuid,text,text) to authenticated;

create or replace function public.disable_push_device(p_device_token text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then return; end if;
  update public.push_devices
     set enabled = false, updated_at = now()
   where user_id = auth.uid()
     and device_token = lower(trim(p_device_token));
end
$$;

revoke all on function public.disable_push_device(text) from public, anon;
grant execute on function public.disable_push_device(text) to authenticated;

create or replace function public.dispatch_alert_to_apns()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform net.http_post(
    url := 'https://mzqwjyantyvizwbzetwf.supabase.co/functions/v1/vet-ai-apns-push',
    body := jsonb_build_object('alert_id', new.id),
    headers := jsonb_build_object('Content-Type', 'application/json'),
    timeout_milliseconds := 5000
  );
  return new;
exception when others then
  raise warning 'Vet AI APNs dispatch queue failed for alert %: %', new.id, sqlerrm;
  return new;
end
$$;

revoke all on function public.dispatch_alert_to_apns() from public, anon, authenticated;

drop trigger if exists vet_ai_alert_apns_push on public.alerts;
create trigger vet_ai_alert_apns_push
after insert on public.alerts
for each row execute function public.dispatch_alert_to_apns();
