create table if not exists public.admin_push_devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  platform text not null default 'ios' check (platform in ('ios')),
  device_token text not null unique,
  environment text not null default 'production' check (environment in ('production','sandbox')),
  enabled boolean not null default true,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists admin_push_devices_enabled_idx on public.admin_push_devices(user_id,enabled) where enabled=true;
alter table public.admin_push_devices enable row level security;
revoke all on public.admin_push_devices from anon, authenticated;
grant all on public.admin_push_devices to service_role;

create table if not exists public.admin_support_push_deliveries (
  id bigint generated by default as identity primary key,
  message_id uuid not null references public.support_messages(id) on delete cascade,
  admin_push_device_id uuid not null references public.admin_push_devices(id) on delete cascade,
  status text not null default 'sending' check (status in ('sending','sent','failed')),
  apns_id text,
  error text,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  unique(message_id,admin_push_device_id)
);
alter table public.admin_support_push_deliveries enable row level security;
revoke all on public.admin_support_push_deliveries from anon, authenticated;
grant all on public.admin_support_push_deliveries to service_role;

create or replace function public.register_admin_push_device(p_device_token text,p_environment text default 'production')
returns uuid language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid(); v_id uuid; v_token text:=lower(trim(p_device_token)); v_environment text:=lower(trim(coalesce(p_environment,'production')));
begin
  if v_user is null then raise exception 'Authentication required'; end if;
  if not public.is_admin_account(null) then raise exception 'Admin access denied'; end if;
  if v_token !~ '^[0-9a-f]{64,}$' then raise exception 'Invalid APNs device token'; end if;
  if v_environment not in ('production','sandbox') then v_environment:='production'; end if;
  insert into public.admin_push_devices(user_id,platform,device_token,environment,enabled,last_seen_at,updated_at)
  values(v_user,'ios',v_token,v_environment,true,now(),now())
  on conflict(device_token) do update set user_id=excluded.user_id,environment=excluded.environment,enabled=true,last_seen_at=now(),updated_at=now()
  returning id into v_id;
  return v_id;
end; $$;
revoke all on function public.register_admin_push_device(text,text) from public,anon;
grant execute on function public.register_admin_push_device(text,text) to authenticated;

create or replace function public.disable_admin_push_device(p_device_token text)
returns void language plpgsql security definer set search_path='' as $$
begin
  if auth.uid() is null then return; end if;
  update public.admin_push_devices set enabled=false,updated_at=now()
  where user_id=auth.uid() and device_token=lower(trim(p_device_token));
end; $$;
revoke all on function public.disable_admin_push_device(text) from public,anon;
grant execute on function public.disable_admin_push_device(text) to authenticated;

create or replace function public.dispatch_support_message_to_admin_push()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if new.sender_role <> 'user' then return new; end if;
  perform net.http_post(
    url := 'https://mzqwjyantyvizwbzetwf.supabase.co/functions/v1/admin-support-push',
    body := jsonb_build_object('message_id',new.id),
    headers := jsonb_build_object('Content-Type','application/json'),
    timeout_milliseconds := 5000
  );
  return new;
exception when others then
  raise warning 'Vet AI admin support push queue failed for message %: %',new.id,sqlerrm;
  return new;
end; $$;
revoke all on function public.dispatch_support_message_to_admin_push() from public,anon,authenticated;

drop trigger if exists vet_ai_support_admin_push on public.support_messages;
create trigger vet_ai_support_admin_push after insert on public.support_messages for each row execute function public.dispatch_support_message_to_admin_push();
