-- Vet AI support voice notes: allow the WAV payload generated by the
-- cross-platform support recorder to be stored in the private support bucket.
-- The bucket remains private and all existing RLS policies stay unchanged.

update storage.buckets
set allowed_mime_types = case
  when allowed_mime_types is null then array['audio/wav']::text[]
  when not ('audio/wav' = any(allowed_mime_types))
    then array_append(allowed_mime_types, 'audio/wav')
  else allowed_mime_types
end
where id = 'support-attachments';
