-- Vet AI support messages sent by staff must notify the farm/customer too.
-- Customer -> admin delivery already exists separately.

create table if not exists public.customer_support_push_deliveries (
  id bigint generated by default as identity primary key,
  message_id uuid not null references public.support_messages(id) on delete cascade,
  push_device_id uuid not null references public.push_devices(id) on delete cascade,
  status text not null default 'sending' check (status in ('sending','sent','failed')),
  apns_id text,
  error text,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  unique (message_id, push_device_id)
);

create index if not exists customer_support_push_deliveries_message_idx
  on public.customer_support_push_deliveries(message_id, created_at desc);

alter table public.customer_support_push_deliveries enable row level security;
revoke all on table public.customer_support_push_deliveries from anon, authenticated;
grant all on table public.customer_support_push_deliveries to service_role;
grant usage, select on sequence public.customer_support_push_deliveries_id_seq to service_role;

create or replace function public.dispatch_support_message_to_customer_push()
returns trigger
language plpgsql
security definer
set search_path to ''
as $$
begin
  if new.sender_role <> 'support' then
    return new;
  end if;

  perform net.http_post(
    url := 'https://mzqwjyantyvizwbzetwf.supabase.co/functions/v1/customer-support-push',
    body := jsonb_build_object('message_id', new.id),
    headers := jsonb_build_object('Content-Type', 'application/json'),
    timeout_milliseconds := 5000
  );
  return new;
exception when others then
  raise warning 'Vet AI customer support push queue failed for message %: %', new.id, sqlerrm;
  return new;
end;
$$;

revoke all on function public.dispatch_support_message_to_customer_push() from public, anon, authenticated;
grant execute on function public.dispatch_support_message_to_customer_push() to service_role;

drop trigger if exists vet_ai_support_customer_push on public.support_messages;
create trigger vet_ai_support_customer_push
after insert on public.support_messages
for each row execute function public.dispatch_support_message_to_customer_push();
