create extension if not exists pg_cron;

alter table public.animal_medications
  add column if not exists dose_interval_hours integer;

alter table public.animal_medications
  drop constraint if exists animal_medications_dose_interval_hours_check;

alter table public.animal_medications
  add constraint animal_medications_dose_interval_hours_check
  check (dose_interval_hours is null or dose_interval_hours between 1 and 336);

create table if not exists public.care_reminder_dispatches (
  id bigint generated by default as identity primary key,
  farm_id uuid not null references public.farms(id) on delete cascade,
  animal_id uuid references public.animals(id) on delete cascade,
  reminder_type text not null check (reminder_type in ('vaccination_due','vaccination_overdue','medication_dose')),
  source_id uuid not null,
  reminder_key text not null unique,
  scheduled_for timestamptz not null,
  alert_id uuid references public.alerts(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists care_reminder_dispatches_farm_created_idx
  on public.care_reminder_dispatches (farm_id, created_at desc);
create index if not exists care_reminder_dispatches_source_idx
  on public.care_reminder_dispatches (source_id, reminder_type);

alter table public.care_reminder_dispatches enable row level security;

drop policy if exists care_reminder_dispatches_member_select on public.care_reminder_dispatches;
create policy care_reminder_dispatches_member_select
on public.care_reminder_dispatches
for select to authenticated
using (public.vet_is_farm_member(farm_id));

revoke insert, update, delete on public.care_reminder_dispatches from anon, authenticated;
grant select on public.care_reminder_dispatches to authenticated;

create or replace function public.process_care_reminders()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  r record;
  claimed_id bigint;
  created_alert_id uuid;
  v_vaccination_due integer := 0;
  v_vaccination_overdue integer := 0;
  v_medication integer := 0;
  v_key text;
  v_label text;
begin
  for r in
    select
      v.id,
      v.farm_id,
      v.animal_id,
      v.vaccine_name,
      v.dose,
      v.due_at,
      coalesce(nullif(trim(a.name), ''), nullif(trim(a.external_id), ''), nullif(trim(a.species), ''), 'Animal') as animal_label
    from public.animal_vaccinations v
    left join public.animals a on a.id = v.animal_id
    where v.status not in ('administered','cancelled')
      and v.due_at <= now() + interval '24 hours'
      and v.due_at >= now() - interval '365 days'
  loop
    if r.due_at < now() then
      v_key := 'vaccination:' || r.id::text || ':overdue';
      v_label := 'Vaccination overdue';
    else
      v_key := 'vaccination:' || r.id::text || ':due';
      v_label := 'Vaccination due soon';
    end if;

    claimed_id := null;
    insert into public.care_reminder_dispatches (
      farm_id, animal_id, reminder_type, source_id, reminder_key, scheduled_for
    ) values (
      r.farm_id,
      r.animal_id,
      case when r.due_at < now() then 'vaccination_overdue' else 'vaccination_due' end,
      r.id,
      v_key,
      r.due_at
    )
    on conflict (reminder_key) do nothing
    returning id into claimed_id;

    if claimed_id is not null then
      insert into public.alerts (
        farm_id, animal_id, risk, title, details, source, metric, threshold_text, value_numeric
      ) values (
        r.farm_id,
        r.animal_id,
        'yellow',
        v_label || ': ' || coalesce(r.vaccine_name, 'Vaccination'),
        r.animal_label || ' · ' ||
          case when r.due_at < now()
            then 'Scheduled vaccination is overdue.'
            else 'Scheduled vaccination is due within 24 hours.'
          end ||
          case when r.dose is null or trim(r.dose) = '' then '' else ' Dose: ' || r.dose end,
        'care_reminder',
        case when r.due_at < now() then 'vaccination_overdue' else 'vaccination_due' end,
        r.due_at::text,
        null
      ) returning id into created_alert_id;

      update public.care_reminder_dispatches
      set alert_id = created_alert_id
      where id = claimed_id;

      if r.due_at < now() then
        v_vaccination_overdue := v_vaccination_overdue + 1;
        update public.animal_vaccinations
        set status = 'missed'
        where id = r.id and status not in ('administered','cancelled','missed');
      else
        v_vaccination_due := v_vaccination_due + 1;
        update public.animal_vaccinations
        set status = 'due'
        where id = r.id and status = 'planned';
      end if;
    end if;
  end loop;

  for r in
    select
      m.id,
      m.farm_id,
      m.animal_id,
      m.medication_name,
      m.dose,
      m.route,
      m.frequency,
      m.next_dose_at,
      coalesce(nullif(trim(a.name), ''), nullif(trim(a.external_id), ''), nullif(trim(a.species), ''), 'Animal') as animal_label
    from public.animal_medications m
    left join public.animals a on a.id = m.animal_id
    where m.status = 'active'
      and m.next_dose_at is not null
      and m.next_dose_at <= now() + interval '30 minutes'
      and m.next_dose_at >= now() - interval '24 hours'
  loop
    v_key := 'medication:' || r.id::text || ':dose:' || to_char(r.next_dose_at at time zone 'UTC', 'YYYYMMDDHH24MI');
    claimed_id := null;

    insert into public.care_reminder_dispatches (
      farm_id, animal_id, reminder_type, source_id, reminder_key, scheduled_for
    ) values (
      r.farm_id,
      r.animal_id,
      'medication_dose',
      r.id,
      v_key,
      r.next_dose_at
    )
    on conflict (reminder_key) do nothing
    returning id into claimed_id;

    if claimed_id is not null then
      insert into public.alerts (
        farm_id, animal_id, risk, title, details, source, metric, threshold_text, value_numeric
      ) values (
        r.farm_id,
        r.animal_id,
        'yellow',
        'Medication dose due: ' || coalesce(r.medication_name, 'Medication'),
        r.animal_label || ' · Dose is due now' ||
          case when r.dose is null or trim(r.dose) = '' then '' else '. Dose: ' || r.dose end ||
          case when r.route is null or trim(r.route) = '' then '' else '. Route: ' || r.route end ||
          case when r.frequency is null or trim(r.frequency) = '' then '' else '. ' || r.frequency end,
        'care_reminder',
        'medication_dose',
        r.next_dose_at::text,
        null
      ) returning id into created_alert_id;

      update public.care_reminder_dispatches
      set alert_id = created_alert_id
      where id = claimed_id;

      v_medication := v_medication + 1;
    end if;
  end loop;

  return jsonb_build_object(
    'vaccination_due', v_vaccination_due,
    'vaccination_overdue', v_vaccination_overdue,
    'medication_dose', v_medication,
    'processed_at', now()
  );
end;
$$;

revoke all on function public.process_care_reminders() from public, anon, authenticated;
grant execute on function public.process_care_reminders() to service_role, postgres;

do $$
declare
  existing_job bigint;
begin
  select jobid into existing_job
  from cron.job
  where jobname = 'vet-ai-care-reminders'
  order by jobid desc
  limit 1;

  if existing_job is not null then
    perform cron.unschedule(existing_job);
  end if;
end;
$$;

select cron.schedule(
  'vet-ai-care-reminders',
  '*/15 * * * *',
  $cmd$select public.process_care_reminders();$cmd$
);
