create table if not exists public.release_validation_runs (
  id bigint generated by default as identity primary key,
  version text not null,
  status text not null check (status in ('passed','failed','partial')),
  checks jsonb not null default '{}'::jsonb,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.release_validation_runs enable row level security;
revoke all on table public.release_validation_runs from anon, authenticated;
grant select, insert on table public.release_validation_runs to service_role;

create or replace function public.vet_ai_v102_transactional_smoke()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_farm uuid;
  v_user uuid;
  v_animal uuid;
  v_assessment uuid;
  v_followups integer := 0;
  v_offsets integer[] := '{}';
  v_vaccination uuid;
  v_medication uuid;
  v_result jsonb := '{}'::jsonb;
begin
  select f.id, f.owner_id
    into v_farm, v_user
  from public.farms f
  where f.owner_id is not null
  order by f.created_at
  limit 1;

  if v_farm is null then
    return jsonb_build_object(
      'ok', false,
      'reason', 'no_farm_available_for_transactional_validation',
      'rolled_back', true
    );
  end if;

  begin
    insert into public.animals (
      farm_id, animal_group, external_id, name, species, active
    ) values (
      v_farm, 'livestock', '__v102_transactional__',
      'V102 transient validation', 'cattle', true
    ) returning id into v_animal;

    insert into public.assessments (
      farm_id, animal_id, created_by, media_path, symptom_notes,
      animal_group, species_code, risk, status, ai_analysis,
      ai_model, ai_generated_at
    ) values (
      v_farm, v_animal, v_user, 'v102/transactional-placeholder.jpg',
      'V102 transient end-to-end validation', 'livestock', 'cattle',
      'insufficient_data', 'draft',
      jsonb_build_object('summary', 'V102 transactional validation'),
      'v102-smoke', now()
    ) returning id into v_assessment;

    select count(*), coalesce(array_agg(offset_hours order by offset_hours), '{}')
      into v_followups, v_offsets
    from public.animal_ai_followups
    where assessment_id = v_assessment;

    if v_followups <> 3 or v_offsets <> array[12,24,48] then
      raise exception 'V102 follow-up scheduling mismatch: count %, offsets %',
        v_followups, v_offsets;
    end if;

    insert into public.animal_vaccinations (
      farm_id, animal_id, vaccine_name, dose, due_at, status, created_by
    ) values (
      v_farm, v_animal, 'V102 transient vaccine', 'test',
      now() + interval '48 hours', 'planned', v_user
    ) returning id into v_vaccination;

    insert into public.animal_medications (
      farm_id, animal_id, medication_name, dose, route, frequency,
      starts_at, next_dose_at, dose_interval_hours, status, created_by
    ) values (
      v_farm, v_animal, 'V102 transient medication', 'test', 'test',
      'every 12 hours', now(), now() + interval '12 hours', 12,
      'active', v_user
    ) returning id into v_medication;

    if not exists (
      select 1 from public.animal_vaccinations where id = v_vaccination
    ) then
      raise exception 'V102 vaccination write path failed';
    end if;

    if not exists (
      select 1 from public.animal_medications
      where id = v_medication and dose_interval_hours = 12
    ) then
      raise exception 'V102 medication write path failed';
    end if;

    v_result := jsonb_build_object(
      'ok', true,
      'animal_write', true,
      'assessment_animal_link', true,
      'followup_trigger', true,
      'followup_count', v_followups,
      'followup_offsets_hours', to_jsonb(v_offsets),
      'vaccination_write', true,
      'medication_write', true,
      'dose_interval_hours', 12,
      'external_notifications_sent', false
    );

    raise exception 'V102_ROLLBACK_SENTINEL';
  exception
    when raise_exception then
      if sqlerrm <> 'V102_ROLLBACK_SENTINEL' then
        raise;
      end if;
  end;

  return v_result || jsonb_build_object('rolled_back', true);
end;
$$;

revoke all on function public.vet_ai_v102_transactional_smoke() from public;
revoke all on function public.vet_ai_v102_transactional_smoke() from authenticated;
grant execute on function public.vet_ai_v102_transactional_smoke() to service_role;

create or replace function public.vet_ai_v102_record_validation(
  p_version text,
  p_status text,
  p_checks jsonb,
  p_notes text default null
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id bigint;
begin
  if p_status not in ('passed','failed','partial') then
    raise exception 'Invalid validation status';
  end if;
  insert into public.release_validation_runs(version,status,checks,notes)
  values (p_version,p_status,coalesce(p_checks,'{}'::jsonb),p_notes)
  returning id into v_id;
  return v_id;
end;
$$;

revoke all on function public.vet_ai_v102_record_validation(text,text,jsonb,text) from public, anon, authenticated;
grant execute on function public.vet_ai_v102_record_validation(text,text,jsonb,text) to service_role;
